# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.10.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Closed vs. opened issues
  parameters:
    - name: repoId
      value: '23083156'
  content:
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: "This issue is for:
          [https://www.notion.so/mui-org/KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c?\
          pvs=4#6585efdaa9d24a66a60a2e74e1613cae](https://www.notion.so/mui-org\
          /KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c?pvs=4#6585efdaa9d24a66a60a2e74\
          e1613cae)"
        mode: markdown
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            (() => {
              const timeSpanInMonths = 3
              let totalOpened = 0
              let totalClosed = 0

              for (let i = 0; i < timeSpanInMonths; i++) {
                totalClosed = +issuesOpenedVsClosedRatio.data.data[i].closed
                totalOpened = +issuesOpenedVsClosedRatio.data.data[i].opened
              }

              return (totalOpened / totalClosed).toFixed(2)
            })()
        unit: ratio
        problem: 2
        warning: 2
        lowerIsBetter: true
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            (() => {
              return "Based on the last 3 months"
            })()
  queries:
    - name: issuesOpenedVsClosedRatio
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://api.ossinsight.io/q/analyze-issue-opened-and-closed?repoId=${parameters.repoId}`
        searchParams: []
        headers: []
        method: GET
      parameters:
        - name: repoId
          value:
            $$jsExpression: |
              page.parameters.repoId
  display: shell
  alias:
    - 2413lvx
  displayName: Closed vs. opened issues
