name: 'Publish Preparation'
description: 'Common setup steps for publishing MUI packages (after checkout)'

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 22.19.0
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    # Ensure npm 11.5.1 or later is installed
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    - name: Build packages
      shell: bash
      run: pnpm run release:build
