name: 'Publish Preparation'
description: 'Common setup steps for publishing MUI packages (after checkout)'

inputs:
  skip-build:
    description: 'Whether to skip building packages after installing dependencies'
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: 22.19.0
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    # Ensure npm 11.5.1 or later is installed
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    - name: Build packages
      if: ${{ !inputs.skip-build }}
      shell: bash
      run: pnpm run release:build
