name: Publish preparation

description: Common setup steps for publishing MUI packages (after checkout)

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: '22.22.3'
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        package-manager-cache: false
    # Ensure npm 11.5.1 or later is installed
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    - name: Build packages
      shell: bash
      run: pnpm run release:build
