# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Community Core
  content:
    - component: DataGrid
      name: DataGrid
      layout:
        columnSize: 1
      props:
        rows:
          $$jsExpression: >
            PRsOpenandReviewedQuery.data.map((item) => ({
              ...item, // use the spread operator to copy existing properties
              ratio: Math.round((item.reviewed * 100) / item.opened) / 100, // add a new property to each object
            }))
        columns:
          - field: event_month
            type: string
            width: 105
          - field: reviewed_by
            type: string
            width: 165
          - field: reviewed
            type: number
            width: 138
          - field: opened
            type: number
            width: 151
          - field: ratio
            type: number
            width: 141
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: Community PRs reviews
    - component: Chart
      name: reviews
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: michaldudak
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "michaldudak")
            xKey: event_month
            yKey: reviewed
            color: '#1976d2'
          - kind: line
            label: mnajdova
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mnajdova")
            xKey: event_month
            yKey: reviewed
            color: '#9c27b0'
          - label: siriwatknp
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "siriwatknp")
            color: '#e91e63'
            xKey: event_month
            yKey: reviewed
          - label: mj12albert
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mj12albert")
            color: '#009688'
            xKey: event_month
            yKey: reviewed
          - label: DiegoAndai
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "DiegoAndai")
            color: '#ff5722'
            xKey: event_month
            yKey: reviewed
          - label: brijeshb42
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "brijeshb42")
            color: '#ff9800'
            xKey: event_month
            yKey: reviewed
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: PRs created
    - component: Chart
      name: reviews1
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: michaldudak
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "michaldudak")
            xKey: event_month
            yKey: opened
            color: '#1976d2'
          - kind: line
            label: mnajdova
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mnajdova")
            xKey: event_month
            yKey: opened
            color: '#9c27b0'
          - label: siriwatknp
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "siriwatknp")
            color: '#e91e63'
            xKey: event_month
            yKey: opened
          - label: mj12albert
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mj12albert")
            color: '#009688'
            xKey: event_month
            yKey: opened
          - label: DiegoAndai
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "DiegoAndai")
            color: '#ff5722'
            xKey: event_month
            yKey: opened
          - label: brijeshb42
            kind: line
            data:
              $$jsExpression: |
                [...PRsOpenandReviewedQuery.data]
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "brijeshb42")
            color: '#ff9800'
            xKey: event_month
            yKey: opened
    - component: Text
      name: text2
      layout:
        columnSize: 1
      props:
        value: Community support ratio
    - component: Chart
      name: reviews2
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: michaldudak
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "michaldudak")
            xKey: event_month
            yKey: ratio
            color: '#1976d2'
          - kind: line
            label: mnajdova
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mnajdova")
            xKey: event_month
            yKey: ratio
            color: '#9c27b0'
          - label: siriwatknp
            kind: line
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "siriwatknp")
            color: '#e91e63'
            xKey: event_month
            yKey: ratio
          - label: mj12albert
            kind: line
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "mj12albert")
            color: '#009688'
            xKey: event_month
            yKey: ratio
          - label: DiegoAndai
            kind: line
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "DiegoAndai")
            color: '#ff5722'
            xKey: event_month
            yKey: ratio
          - label: brijeshb42
            kind: line
            data:
              $$jsExpression: >
                [...PRsOpenandReviewedQuery.data]
                  .map((entry) => ({ ...entry, ratio: entry.reviewed / entry.opened }))
                  .reverse()
                  .filter((entry) => entry.reviewed_by === "brijeshb42")
            color: '#ff9800'
            xKey: event_month
            yKey: ratio
    - component: Chart
      name: chart
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: pr_community_count
            data:
              $$jsExpression: |
                PrsPerMonth.data
            xKey: event_month
            yKey: pr_community_count
            color: '#7cb342'
          - kind: line
            label: pr_maintainers_count
            data:
              $$jsExpression: |
                PrsPerMonth.data
            xKey: event_month
            yKey: pr_maintainers_count
            color: '#27aeef'
        height: 300
  queries:
    - name: PRsOpenandReviewedQuery
      query:
        function: PRsOpenandReviewedQuery
        kind: local
    - name: PrsPerMonth
      query:
        function: functions.ts#PRsPerMonth
        kind: local
      parameters:
        - name: repositoryId
          value: '23083156'
  alias:
    - 9r8fshsf
  displayName: Community Core
