import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdir, rm, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { updatePageIndex } from './updatePageIndex';
import type { PageMetadata } from './metadataToMarkdown';

const TEST_DIR = join(__dirname, '.test-updatePageIndex');

describe('updatePageIndex', () => {
  beforeEach(async () => {
    // Create test directory
    await mkdir(TEST_DIR, { recursive: true });
    await mkdir(join(TEST_DIR, 'components'), { recursive: true });
    await mkdir(join(TEST_DIR, 'components', 'button'), { recursive: true });
  });

  afterEach(async () => {
    // Clean up test directory
    await rm(TEST_DIR, { recursive: true, force: true });
  });

  it('should create new index file when none exists', async () => {
    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    const indexPath = join(TEST_DIR, 'components', 'page.mdx');
    const content = await readFile(indexPath, 'utf-8');

    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Button](./button/page.mdx) - A button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should update existing index file with new page', async () => {
    const indexPath = join(TEST_DIR, 'components', 'page.mdx');
    const existingContent = `# Components

[//]: # 'This file is autogenerated, but the following order can be modified'

- [Checkbox](./checkbox/page.mdx) - A checkbox component.

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Checkbox

A checkbox component.

[Read more](./checkbox/page.mdx)
`;

    await writeFile(indexPath, existingContent, 'utf-8');

    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    const content = await readFile(indexPath, 'utf-8');

    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Checkbox](./checkbox/page.mdx) - A checkbox component.
      - [Button](./button/page.mdx) - A button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Checkbox

      A checkbox component.

      [Read more](./checkbox/page.mdx)

      ## Button

      A button component.

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should update existing page metadata', async () => {
    const indexPath = join(TEST_DIR, 'components', 'page.mdx');
    const existingContent = `# Components

[//]: # 'This file is autogenerated, but the following order can be modified'

- [Button](./button/page.mdx) - Old description.

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old description.

[Read more](./button/page.mdx)
`;

    await writeFile(indexPath, existingContent, 'utf-8');

    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'Updated button component with new features.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    const content = await readFile(indexPath, 'utf-8');

    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Button](./button/page.mdx) - Updated button component with new features.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      Updated button component with new features.

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should handle custom index file name', async () => {
    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
      indexFileName: 'index.mdx',
    });

    const indexPath = join(TEST_DIR, 'components', 'index.mdx');
    const content = await readFile(indexPath, 'utf-8');

    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Button](./button/page.mdx) - A button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should handle metadata with openGraph', async () => {
    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
      keywords: ['interactive', 'input'],
      openGraph: {
        title: 'Button Component',
        description: 'A comprehensive button component.',
        images: [
          {
            url: 'https://example.com/button.png',
            width: 800,
            height: 600,
            alt: 'Button preview',
          },
        ],
      },
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    const indexPath = join(TEST_DIR, 'components', 'page.mdx');
    const content = await readFile(indexPath, 'utf-8');

    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Button Component](./button/page.mdx) - A comprehensive button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button Component

      A comprehensive button component.

      ![Button preview](https://example.com/button.png)

      - Keywords: interactive, input

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should preserve order from existing index', async () => {
    const indexPath = join(TEST_DIR, 'components', 'page.mdx');
    const existingContent = `# Components

[//]: # 'This file is autogenerated, but the following order can be modified'

- [Checkbox](./checkbox/page.mdx) - A checkbox component.
- [Input](./input/page.mdx) - An input component.

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Checkbox

A checkbox component.

[Read more](./checkbox/page.mdx)

## Input

An input component.

[Read more](./input/page.mdx)
`;

    await writeFile(indexPath, existingContent, 'utf-8');

    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'components', 'button', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    const content = await readFile(indexPath, 'utf-8');

    // Button should be added at the end, preserving Checkbox -> Input order
    expect(content).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Checkbox](./checkbox/page.mdx) - A checkbox component.
      - [Input](./input/page.mdx) - An input component.
      - [Button](./button/page.mdx) - A button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Checkbox

      A checkbox component.

      [Read more](./checkbox/page.mdx)

      ## Input

      An input component.

      [Read more](./input/page.mdx)

      ## Button

      A button component.

      [Read more](./button/page.mdx)
      "
    `);
  });

  it('should correctly resolve index path from nested page structure', async () => {
    // Test the actual path structure: app/components/checkbox/page.mdx -> app/components/page.mdx
    await mkdir(join(TEST_DIR, 'app'), { recursive: true });
    await mkdir(join(TEST_DIR, 'app', 'components'), { recursive: true });
    await mkdir(join(TEST_DIR, 'app', 'components', 'checkbox'), { recursive: true });

    const metadata: PageMetadata = {
      slug: 'checkbox',
      path: './checkbox/page.mdx',
      title: 'Checkbox',
      description: 'A checkbox component.',
    };

    await updatePageIndex({
      pagePath: join(TEST_DIR, 'app', 'components', 'checkbox', 'page.mdx'),
      metadata,
      indexTitle: 'Components',
    });

    // Index should be at app/components/page.mdx (not app/components/checkbox/page.mdx)
    const indexPath = join(TEST_DIR, 'app', 'components', 'page.mdx');
    const content = await readFile(indexPath, 'utf-8');

    expect(content).toContain('# Components');
    expect(content).toContain('[Checkbox](./checkbox/page.mdx)');
    expect(content).toContain('A checkbox component.');
  });

  it('should derive index title from directory name when not provided', async () => {
    // Create a directory with kebab-case name
    await mkdir(join(TEST_DIR, 'ui-components'), { recursive: true });
    await mkdir(join(TEST_DIR, 'ui-components', 'button'), { recursive: true });

    const metadata: PageMetadata = {
      slug: 'button',
      path: './button/page.mdx',
      title: 'Button',
      description: 'A button component.',
    };

    // Don't provide indexTitle - should derive "Ui Components" from "ui-components"
    await updatePageIndex({
      pagePath: join(TEST_DIR, 'ui-components', 'button', 'page.mdx'),
      metadata,
    });

    const indexPath = join(TEST_DIR, 'ui-components', 'page.mdx');
    const content = await readFile(indexPath, 'utf-8');

    expect(content).toContain('# Ui Components');
    expect(content).toMatchInlineSnapshot(`
      "# Ui Components

      [//]: # 'This file is autogenerated, but the following order can be modified'

      - [Button](./button/page.mdx) - A button component.

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)
      "
    `);
  });
});
