# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.5.2/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Open PRs
  parameters:
    - name: repo
      value: material-ui
    - name: warning
      value: '50'
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            openPRs.data.total_count
        unit: ' open PRs'
        warning:
          $$jsExpression: |
            page.parameters.warning
        problem:
          $$jsExpression: |
            parseInt(page.parameters.warning) * 1.5
        lowerIsBetter: true
  queries:
    - name: openPRs
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:pull-request is:open -is:draft
                repo:mui/${parameters.repository}`
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: "`Bearer ${parameters.GITHUB_TOKEN}`\n" },
            },
          ]
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repo
        - name: GITHUB_TOKEN
          value:
            $$env: GITHUB_TOKEN
  display: shell
  alias:
    - 39j3h6b
  displayName: Open PRs
