# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.13.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: CI completion time
  alias:
    - fn03hvq
  displayName: CI completion time
  content:
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        mode: markdown
        value:
          "This page has moved to the code-infra-dashboard:
          [CI completion time](https://code-infra-dashboard.onrender.com/kpis)"
  display: shell
