# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: CI completion time
  parameters:
    - name: repository
      value: mui-x
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            Math.round((queryInsights.data.metrics.duration_metrics.median / 60)
            * 100) /
              100
        warning: 15
        problem: 20
        unit: minutes
        lowerIsBetter: true
    - component: Text
      name: Text
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            `Based on the last 7 days (${queryInsights.data.metrics.total_runs}
            runs)`
  queries:
    - name: queryInsights
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://circleci.com/api/v2/insights/github/mui/${parameters.repository}/workflows/pipeline/summary?analytics-segmentation=web-ui-insights&reporting-window=last-7-days&workflow-name=pipeline`
        headers: []
        method: GET
        searchParams: []
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: shell
  alias:
    - fn03hvq
  displayName: CI completion time
