# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Gender in management
  display: shell
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            genderManagement.data != null
              ? Math.round(genderManagement.data * 10) / 10
              : undefined
        warning: 30
        problem: 15
  queries:
    - name: genderManagement
      query:
        function: queryGender.ts#queryGenderManagement
        kind: local
  alias:
    - oEEu_u7
  displayName: Gender in management
