# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.6.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Community per month
  content:
    - component: TextField
      name: slug
      layout:
        columnSize: 1
      props:
        label: Repository slug
        defaultValue: mui/material-ui
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            (() => {
              if (getRepositoryDetails.data) {
                return `Repository ID: ${getRepositoryDetails.data.data.id}`
              } else {
                return "Not found"
              }
            })()
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: 'Community: PRs merged per month'
        variant: h6
        sx:
          mt: 2
    - component: Chart
      name: chart
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: pr_community_count
            data:
              $$jsExpression: >
                PRsPerMonth.rows.map((row) => ({
                  ...row,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 1000) / 10,
                }))
            xKey: event_month
            yKey: pr_community_count
            color: '#7cb342'
          - kind: line
            label: pr_maintainers_count
            data:
              $$jsExpression: >
                PRsPerMonth.rows.map((row) => ({
                  ...row,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 1000) / 10,
                }))
            xKey: event_month
            yKey: pr_maintainers_count
            color: '#27aeef'
          - kind: line
            label: ratio
            data:
              $$jsExpression: >
                PRsPerMonth.rows.map((row) => ({
                  ...row,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 1000) / 10,
                }))
            xKey: event_month
            yKey: ratio
            color: '#ea5545'
        height: 300
    - component: Text
      name: text2
      layout:
        columnSize: 1
      props:
        value: 'Community: Unique contributors per month'
        variant: h6
        sx:
          mt: 2
    - component: Chart
      name: chart1
      layout:
        columnSize: 1
      props:
        data:
          - kind: line
            label: community_count
            data:
              $$jsExpression: >
                ContributorsPerMonth.rows.map((row) => ({
                  ...row,
                  community_count: row.pr_community_count,
                  maintainers_count: row.pr_maintainers_count,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 100) / 100,
                }))
            xKey: event_month
            yKey: community_count
            color: '#7cb342'
          - kind: line
            label: maintainers_count
            data:
              $$jsExpression: >
                ContributorsPerMonth.rows.map((row) => ({
                  ...row,
                  community_count: row.pr_community_count,
                  maintainers_count: row.pr_maintainers_count,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 100) / 100,
                }))
            xKey: event_month
            yKey: maintainers_count
            color: '#27aeef'
          - kind: line
            label: ratio
            data:
              $$jsExpression: >
                ContributorsPerMonth.rows.map((row) => ({
                  ...row,
                  community_count: row.pr_community_count,
                  maintainers_count: row.pr_maintainers_count,
                  ratio:
                    Math.round((row.pr_community_count / row.pr_maintainers_count) * 100) / 100,
                }))
            xKey: event_month
            yKey: ratio
            color: '#ea5545'
        height: 300
  queries:
    - name: PRsPerMonth
      query:
        function: PRsPerMonth
        kind: local
      parameters:
        - name: repositoryId
          value:
            $$jsExpression: |
              getRepositoryDetails.data.data.id
    - name: getRepositoryDetails
      query:
        function: getRepositoryDetails
        kind: local
      parameters:
        - name: slug
          value:
            $$jsExpression: |
              slug.value
    - name: ContributorsPerMonth
      query:
        function: ContributorsPerMonth
        kind: local
      parameters:
        - name: repositoryId
          value:
            $$jsExpression: |
              getRepositoryDetails.data.data.id
  alias:
    - ck33hgb
  displayName: Community per month
