# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.6.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Bundle sizes
  parameters:
    - name: baseRef
      value: master
    - name: baseCommit
      value: a25a365a4c66738f358ecd745bf3727c0ca9d5b6
    - name: circleCIBuildNumber
      value: '759455'
  content:
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: '# Size comparison'
        variant: h2
        mode: markdown
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
        height: 572
      props:
        rows:
          $$jsExpression: |
            bundleSizes.data
        columns:
          - field: name
            type: string
            headerName: Bundle
            width: 334
          - field: absoluteDiff.parsed
            type: codeComponent
            codeComponent: Diff
            headerName: Size change
            align: right
          - field: relativeDiff.parsed
            type: codeComponent
            codeComponent: Percent
            width: 111
            headerName: Size %
            align: right
          - field: current.parsed
            type: number
            headerName: Size
            numberFormat:
              kind: preset
              preset: bytes
          - field: absoluteDiff.gzip
            type: codeComponent
            headerName: Gzip change
            codeComponent: Diff
            align: right
          - field: relativeDiff.gzip
            type: codeComponent
            codeComponent: Percent
            headerName: Gzip %
            align: right
          - field: current.gzip
            type: number
            numberFormat:
              kind: preset
              preset: bytes
            headerName: Gzip
        height: 534
        density: compact
  queries:
    - name: bundleSizes
      query:
        function: bundleSizeQueries.ts#getBundleSizes
        kind: local
      parameters:
        - name: baseRef
          value:
            $$jsExpression: |
              page.parameters.baseRef
        - name: baseCommit
          value:
            $$jsExpression: |
              page.parameters.baseCommit
        - name: circleCIBuildNumber
          value:
            $$jsExpression: |
              page.parameters.circleCIBuildNumber
  alias:
    - h71gdad
  displayName: Bundle sizes
