# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Zendesk satisfaction score
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            Math.round(
              (satisfactionRating.data.filter((rating) => rating.score === "good").length /
                satisfactionRating.data.length) *
                100
            )
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            `Number of reviews in the last 4 weeks:
            ${satisfactionRating.data.length}`
  queries:
    - name: satisfactionRating
      query:
        kind: rest
        url: https://mui.zendesk.com/api/v2/satisfaction_ratings
        searchParams:
          - name: start_time
            value:
              $$jsExpression: >
                (() => {
                  const days = 7 * 4
                  return Math.round(new Date().getTime() / 1000) - 3600 * 24 * days
                })()
          - name: score
            value: received
        headers:
          - name: Authorization
            value:
              $$env: ZENDESK
        method: GET
        transform: |-
          return Object.values(data.satisfaction_ratings.reduce((acc, item) => {
            // only keep the latest
            acc[item.ticket_id] = {
              score: item.score,
            };
            return acc;
          }, {}));
        transformEnabled: true
  alias:
    - xu1r3hzj
  displayName: Zendesk satisfaction score
