export const extensionMap: Record<string, string> = {
  '.js': 'javascript',
  '.ts': 'typescript',
  '.jsx': 'javascript',
  '.tsx': 'typescript',
  '.json': 'json',
  '.md': 'markdown',
  '.html': 'html',
  '.css': 'css',
  '.py': 'python',
  '.java': 'java',
  '.c': 'c',
  '.cpp': 'cpp',
  '.go': 'go',
  '.rb': 'ruby',
  '.php': 'php',
  '.sh': 'bash',
  '.sql': 'sql',
  '.yaml': 'yaml',
  '.xml': 'xml',
  '.txt': 'plaintext',
};
