# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.13.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Query OSS Insight
  display: shell
  authorization:
    allowAll: true
  content:
    - component: TextField
      name: slug
      props:
        label: Repository slug
        defaultValue: mui/material-ui
      layout:
        columnSize: 1
    - component: Text
      name: text
      layout:
        columnSize: 1
        horizontalAlign: start
        verticalAlign: center
      props:
        value:
          $$jsExpression: |
            (() => {
              if (getRepositoryDetails.data) {
                return `Repository ID: ${getRepositoryDetails.data.data.id}`
              } else {
                return "Not found"
              }
            })()
    - component: codeComponent.Textarea
      name: textarea
    - component: Button
      name: button
      props:
        content: Run query
        onClick:
          $$jsExpressionAction: queryOssInsight.fetch()
        loading:
          $$jsExpression: queryOssInsight.isLoading
    - component: Paper
      name: paper
      children:
        - component: Text
          name: text1
          props:
            value:
              $$jsExpression: queryOssInsight.error?.message ?? ''
    - component: codeComponent.AutoDataGrid
      name: autoDataGrid
      props:
        rows:
          $$jsExpression: queryOssInsight.rows
  queries:
    - name: queryOssInsight
      mode: mutation
      query:
        function: queryOssInsight.ts#queryOssInsight
        kind: local
      parameters:
        - name: repositoryId
          value:
            $$jsExpression: getRepositoryDetails.data?.data?.id
        - name: query
          value:
            $$jsExpression: textarea.value
      enabled: true
    - name: getRepositoryDetails
      query:
        function: functions.ts#getRepositoryDetails
        kind: local
      parameters:
        - name: slug
          value:
            $$jsExpression: |
              slug.value
  displayName: Query OSS Insight
