# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Waiting for maintainer
  parameters:
    - name: repository
      value: material-ui
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            waitingForMaintainer.data.total_count
        warning: 25
        problem: 50
        unit: ' issues'
        lowerIsBetter: true
  queries:
    - name: waitingForMaintainer
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:issue repo:mui/${parameters.repository} label:"status:
                waiting for maintainer" `
        headers:
          [
            {
              name: Authorization,
              value: { $$jsExpression: "`Bearer ${parameters.GITHUB_TOKEN}`\n" },
            },
          ]
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
        - name: GITHUB_TOKEN
          value:
            $$env: GITHUB_TOKEN
    - name: waitingForMaintainer2
      mode: query
      query:
        function: queryGitHubSearchAPI.ts#queryGitHubSearchAPI
        kind: local
      parameters:
        - name: queryInput
          value:
            $$jsExpression: '`is:issue repo:mui/${page.parameters.repository}
              label:\\"status: waiting for maintainer\\"`'
  display: shell
  alias:
    - hj1i3hqe
  displayName: Waiting for maintainer
