# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Gender in engineering
  parameters:
    - name: department
      value: ''
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            gender1.data != null ? Math.round(gender1.data * 10) / 10 : undefined
        warning: 14
        problem: 7
        lowerIsBetter: false
  queries:
    - name: gender1
      query:
        function: queryGender.ts#queryGender
        kind: local
      parameters:
        - name: department
          value: '256186803'
  display: shell
  alias:
    - ZGrUwtd
  displayName: Gender in engineering
