import { describe, it, expect } from 'vitest';
import {
  metadataToMarkdown,
  markdownToMetadata,
  formatLinkUrl,
  createPageSectionResolver,
} from './metadataToMarkdown';
import { mergeMetadataMarkdown, mergeMetadataPages } from './mergeMetadataMarkdown';
import { indexRelativePagePath } from './syncPageIndex';
import type { PagesMetadata } from './metadataToMarkdown';

describe('group-aware index rendering', () => {
  it('renders sections with a Details wrapper', () => {
    const data: PagesMetadata = {
      title: 'React',
      sections: [{ title: 'Overview' }, { title: 'Utilities' }],
      pages: [
        {
          slug: 'quick-start',
          path: './(overview)/quick-start/page.mdx',
          title: 'Quick start',
          description: 'Get started.',
          sectionIndex: 0,
        },
        {
          slug: 'userender',
          path: './(utils)/use-render/page.mdx',
          title: 'useRender',
          description: 'Render prop helper.',
          sectionIndex: 1,
        },
      ],
    };

    const result = metadataToMarkdown(data, { path: 'src/app/react/page.mdx' });

    expect(result).toMatchInlineSnapshot(`
      "# React

      [//]: # 'This section is autogenerated, but the following list order, title, and [Tag]s can be modified, but nothing within the parentheses.'

      ## Overview

      - Quick start - ([Outline](#quick-start), [Contents](<./(overview)/quick-start/page.mdx>))

      ## Utilities

      - useRender - ([Outline](#userender), [Contents](<./(utils)/use-render/page.mdx>))

      [//]: # 'This section is autogenerated, DO NOT EDIT AFTER THIS LINE, run: pnpm docs:validate react'

      ## Details

      ### Quick start

      Get started.

      [Read more](<./(overview)/quick-start/page.mdx>)

      ### useRender

      Render prop helper.

      [Read more](<./(utils)/use-render/page.mdx>)

      [//]: # 'The above section is autogenerated, but the remainder of the file can be modified.'

      export const metadata =
        /** @type {import('@mui/internal-docs-infra/createSitemap/types').NextMetadata} */ ({
          robots: {
            index: false,
          },
          other: {
            audience: 'private',
          },
        });
      "
    `);
  });

  it('round-trips: parse recovers sections/placement/detailsSectionTitle and re-render is stable', async () => {
    const data: PagesMetadata = {
      title: 'React',
      sections: [{ title: 'Overview' }, { title: 'Utilities' }],
      pages: [
        {
          slug: 'quick-start',
          path: './(overview)/quick-start/page.mdx',
          title: 'Quick start',
          description: 'Get started.',
          sectionIndex: 0,
        },
        {
          slug: 'userender',
          path: './(utils)/use-render/page.mdx',
          title: 'useRender',
          description: 'Render prop helper.',
          sectionIndex: 1,
        },
      ],
    };

    const markdown = metadataToMarkdown(data, { path: 'src/app/react/page.mdx' });
    const parsed = await markdownToMetadata(markdown);

    expect(parsed?.sections).toEqual([{ title: 'Overview' }, { title: 'Utilities' }]);
    expect(parsed?.detailsSectionTitle).toBe('Details');
    expect(parsed?.pages.map((page) => [page.path, page.sectionIndex])).toEqual([
      ['./(overview)/quick-start/page.mdx', 0],
      ['./(utils)/use-render/page.mdx', 1],
    ]);

    // Re-rendering the parsed metadata reproduces the same markdown.
    const reserialized = metadataToMarkdown(parsed!, { path: 'src/app/react/page.mdx' });
    expect(reserialized).toBe(markdown);
  });

  it('groups pages with no route group of their own under a human heading (round-trip)', async () => {
    // A section's identity is its position, not a route group, so pages whose paths have no
    // route group can still be grouped under a heading a human added.
    const data: PagesMetadata = {
      title: 'Components',
      sections: [{ title: 'Grouping heading' }],
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
          sectionIndex: 0,
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'A checkbox component.',
          sectionIndex: 0,
        },
      ],
    };

    const markdown = metadataToMarkdown(data, { path: 'src/app/components/page.mdx' });
    const parsed = await markdownToMetadata(markdown);

    expect(parsed?.sections).toEqual([{ title: 'Grouping heading' }]);
    expect(parsed?.pages.map((page) => page.sectionIndex)).toEqual([0, 0]);
    expect(parsed?.pages.map((page) => page.description)).toEqual([
      'A button component.',
      'A checkbox component.',
    ]);
    expect(metadataToMarkdown(parsed!, { path: 'src/app/components/page.mdx' })).toBe(markdown);
  });

  it('keeps a heading whose only pages are external links (round-trip)', async () => {
    // A heading grouping only external links (no route group anywhere under it) must survive:
    // its pages carry its section index, so the heading is not dropped on parse.
    const data: PagesMetadata = {
      title: 'React',
      sections: [{ title: 'Resources' }],
      pages: [
        {
          slug: 'figma',
          path: 'https://figma.com/mui',
          title: 'Figma kit',
          tags: ['External'],
          skipDetailSection: true,
          sectionIndex: 0,
        },
      ],
    };

    const markdown = metadataToMarkdown(data, { path: 'src/app/react/page.mdx' });
    // The heading and its external link are both rendered (heading not dropped).
    expect(markdown).toContain('## Resources');
    expect(markdown.indexOf('## Resources')).toBeLessThan(markdown.indexOf('Figma kit'));

    const parsed = await markdownToMetadata(markdown);
    expect(parsed?.sections).toEqual([{ title: 'Resources' }]);
    expect(parsed?.pages[0]?.sectionIndex).toBe(0);
    expect(metadataToMarkdown(parsed!, { path: 'src/app/react/page.mdx' })).toBe(markdown);
  });
});

describe('group-aware index merge', () => {
  it('auto-groups a fresh index, seeding a heading for the first page of each route group', async () => {
    const result = await mergeMetadataMarkdown(
      undefined,
      {
        title: 'React',
        pages: [
          {
            slug: 'accordion',
            path: './(components)/accordion/page.mdx',
            title: 'Accordion',
            description: 'An accordion.',
          },
          {
            slug: 'use-render',
            path: './(utils)/use-render/page.mdx',
            title: 'useRender',
            description: 'Render prop helper.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // Headings are seeded from the route-group folder names, in page-encounter order, with the
    // detail region (### headings) after the editable section list.
    expect(result).toContain('## Components');
    expect(result).toContain('## Utils');
    expect(result.indexOf('## Components')).toBeLessThan(result.indexOf('## Utils'));
    expect(result.indexOf('## Utils')).toBeLessThan(result.indexOf('## Details'));
    expect(result.indexOf('## Details')).toBeLessThan(result.indexOf('### Accordion'));
    expect(result.indexOf('### Accordion')).toBeLessThan(result.indexOf('### useRender'));
  });

  it('routes a new page under its route-group siblings and preserves a renamed heading', async () => {
    const existing = metadataToMarkdown(
      {
        title: 'React',
        sections: [{ title: 'Utilities' }],
        pages: [
          {
            slug: 'use-render',
            path: './(utils)/use-render/page.mdx',
            title: 'useRender',
            description: 'Render prop helper.',
            sectionIndex: 0,
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    const merged = await mergeMetadataMarkdown(
      existing,
      {
        title: 'React',
        pages: [
          {
            slug: 'use-render',
            path: './(utils)/use-render/page.mdx',
            title: 'useRender',
            description: 'Render prop helper.',
          },
          {
            slug: 'merge-props',
            path: './(utils)/merge-props/page.mdx',
            title: 'mergeProps',
            description: 'Merge props helper.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // The renamed heading survives (no re-seeded "## Utils"); the new page joins its sibling.
    expect(merged).toContain('## Utilities');
    expect(merged).not.toContain('## Utils\n');
    const utilitiesBlock = merged.slice(
      merged.indexOf('## Utilities'),
      merged.indexOf('[//]: #', merged.indexOf('## Utilities')),
    );
    expect(utilitiesBlock).toContain('- useRender -');
    // The new page is tagged [New] and placed under the same section.
    expect(utilitiesBlock).toContain('- mergeProps [New] -');
  });

  it('creates a heading for the first page of a new group and the second falls in behind it', async () => {
    const merged = await mergeMetadataMarkdown(
      undefined,
      {
        title: 'React',
        pages: [
          {
            slug: 'accordion',
            path: './(components)/accordion/page.mdx',
            title: 'Accordion',
            description: 'An accordion.',
          },
          {
            slug: 'avatar',
            path: './(components)/avatar/page.mdx',
            title: 'Avatar',
            description: 'An avatar.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // Exactly one "## Components" heading, holding both pages.
    expect(merged.split('## Components')).toHaveLength(2);
    const componentsBlock = merged.slice(
      merged.indexOf('## Components'),
      merged.indexOf('[//]: #', merged.indexOf('## Components')),
    );
    expect(componentsBlock).toContain('- Accordion -');
    expect(componentsBlock).toContain('- Avatar -');
  });

  it('leaves a page with no route group ungrouped (no header-of-one)', async () => {
    const merged = await mergeMetadataMarkdown(
      undefined,
      {
        title: 'React',
        pages: [
          {
            slug: 'intro',
            path: './intro/page.mdx',
            title: 'Intro',
            description: 'Intro page.',
          },
          {
            slug: 'accordion',
            path: './(components)/accordion/page.mdx',
            title: 'Accordion',
            description: 'An accordion.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // The flat page gets no heading of its own and is listed before the first section.
    // (Line-exact check: the `### Intro` detail heading contains `## Intro` as a substring.)
    const lines = merged.split('\n');
    expect(lines).not.toContain('## Intro');
    expect(lines).toContain('## Components');
    expect(merged.indexOf('- Intro')).toBeLessThan(merged.indexOf('## Components'));
  });

  it('removes a deleted page and drops an emptied section without disturbing others', async () => {
    const existing = metadataToMarkdown(
      {
        title: 'React',
        sections: [{ title: 'Overview' }, { title: 'Utilities' }],
        pages: [
          {
            slug: 'quick-start',
            path: './(overview)/quick-start/page.mdx',
            title: 'Quick start',
            description: 'Get started.',
            sectionIndex: 0,
          },
          {
            slug: 'use-render',
            path: './(utils)/use-render/page.mdx',
            title: 'useRender',
            description: 'Render prop helper.',
            sectionIndex: 1,
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // Regeneration no longer lists the (utils) page.
    const merged = await mergeMetadataMarkdown(
      existing,
      {
        title: 'React',
        pages: [
          {
            slug: 'quick-start',
            path: './(overview)/quick-start/page.mdx',
            title: 'Quick start',
            description: 'Get started.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    expect(merged).toContain('## Overview');
    expect(merged).toContain('- Quick start -');
    // The emptied Utilities section and its page are gone.
    expect(merged).not.toContain('## Utilities');
    expect(merged).not.toContain('useRender');
  });

  it('groups consecutive route groups under the outermost group', async () => {
    // Pages that bubbled past two consecutive route groups: the outermost is the section,
    // the inner one is transparent. Two pages sharing the outermost group land together.
    const result = await mergeMetadataMarkdown(
      undefined,
      {
        title: 'React',
        pages: [
          {
            slug: 'checkbox',
            path: './(components)/(inputs)/checkbox/page.mdx',
            title: 'Checkbox',
            description: 'A checkbox.',
          },
          {
            slug: 'avatar',
            path: './(components)/(display)/avatar/page.mdx',
            title: 'Avatar',
            description: 'An avatar.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // A single "## Components" section (from the outermost group), not one per inner group.
    expect(result).toContain('## Components');
    expect(result).not.toContain('## Inputs');
    expect(result).not.toContain('## Display');
    const componentsBlock = result.slice(
      result.indexOf('## Components'),
      result.indexOf('[//]: #', result.indexOf('## Components')),
    );
    expect(componentsBlock).toContain('- Checkbox -');
    expect(componentsBlock).toContain('- Avatar -');
    // Links retain the full route-group path (stripped to the URL only at render time).
    expect(result).toContain('[Contents](<./(components)/(inputs)/checkbox/page.mdx>)');
  });

  it('treats dynamic segments as non-group segments', async () => {
    // Dynamic segments ([slug], [...slug]) are not route groups: a page directly under
    // one is ungrouped, while a route group with a dynamic segment beneath it still groups.
    const result = await mergeMetadataMarkdown(
      undefined,
      {
        title: 'React',
        pages: [
          {
            slug: 'accordion',
            path: './(components)/[variant]/accordion/page.mdx',
            title: 'Accordion',
            description: 'An accordion.',
          },
          {
            slug: 'catch-all',
            path: './[...slug]/page.mdx',
            title: 'Catch All',
            description: 'A dynamic page.',
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    // The route-group page groups (dynamic child is irrelevant to sectioning)...
    expect(result).toContain('## Components');
    const componentsBlock = result.slice(
      result.indexOf('## Components'),
      result.indexOf('[//]: #', result.indexOf('## Components')),
    );
    expect(componentsBlock).toContain('- Accordion -');
    // ...and the dynamic-segment page is ungrouped (listed before the first section, no heading).
    expect(result).not.toContain('## Slug');
    expect(result.indexOf('- Catch All')).toBeLessThan(result.indexOf('## Components'));
  });
});

describe('group-aware index parser edge cases', () => {
  const EDITABLE_MARKER =
    "[//]: # 'This section is autogenerated, but the following list order, title, and [Tag]s can be modified, but nothing within the parentheses.'";
  const DO_NOT_EDIT_MARKER = "[//]: # 'This section is autogenerated, DO NOT EDIT AFTER THIS LINE'";

  it('keeps an empty heading as its own (positional) section without duplicating pages', async () => {
    // A human-added heading with no pages of its own is its own section; the following
    // heading's pages stay under the following heading (no stealing, no duplication).
    const markdown = [
      '# React',
      '',
      EDITABLE_MARKER,
      '',
      '## Placeholder',
      '',
      '## Utilities',
      '',
      '- useRender - ([Outline](#userender), [Contents](./(utils)/use-render/page.mdx))',
      '',
      DO_NOT_EDIT_MARKER,
      '',
      '## Details',
      '',
      '### useRender',
      '',
      'Render prop helper.',
      '',
      '[Read more](./(utils)/use-render/page.mdx)',
      '',
    ].join('\n');

    const parsed = await markdownToMetadata(markdown);

    // Both headings are kept, in order; the page sits under the second one only.
    expect(parsed?.sections).toEqual([{ title: 'Placeholder' }, { title: 'Utilities' }]);
    expect(parsed?.pages).toHaveLength(1);
    expect(parsed?.pages[0]?.sectionIndex).toBe(1);

    // Re-rendering lists the page exactly once (no duplicate under two headings).
    const rerendered = metadataToMarkdown(parsed!, { path: 'src/app/react/page.mdx' });
    expect(rerendered.split('- useRender -')).toHaveLength(2);
    expect(rerendered.split('### useRender')).toHaveLength(2);
  });

  it('places every item under a heading by position, external links included', async () => {
    const markdown = [
      '# React',
      '',
      EDITABLE_MARKER,
      '',
      '## Utilities',
      '',
      '- [llms.txt](/llms.txt) [External]',
      '- useRender - ([Outline](#userender), [Contents](./(utils)/use-render/page.mdx))',
      '',
      DO_NOT_EDIT_MARKER,
      '',
      '## Details',
      '',
      '### useRender',
      '',
      'Render prop helper.',
      '',
    ].join('\n');

    const parsed = await markdownToMetadata(markdown);
    // One section; both the external link and the page are under it (by position).
    expect(parsed?.sections).toEqual([{ title: 'Utilities' }]);
    expect(parsed?.pages.map((page) => page.sectionIndex)).toEqual([0, 0]);
  });

  it('round-trips a non-default section heading depth', async () => {
    const markdown = metadataToMarkdown(
      {
        title: 'React',
        sections: [{ title: 'Utilities', depth: 3 }],
        pages: [
          {
            slug: 'use-render',
            path: './(utils)/use-render/page.mdx',
            title: 'useRender',
            description: 'Render prop helper.',
            sectionIndex: 0,
          },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    expect(markdown).toContain('### Utilities');
    const parsed = await markdownToMetadata(markdown);
    expect(parsed?.sections).toEqual([{ title: 'Utilities', depth: 3 }]);
  });

  it('treats only the first detail-region H2 as the Details wrapper', async () => {
    // A stray H2 inside the detail region must not overwrite the wrapper title or discard
    // the in-progress page's parsed metadata.
    const markdown = [
      '# React',
      '',
      EDITABLE_MARKER,
      '',
      '## Utilities',
      '',
      '- useRender - ([Outline](#userender), [Contents](./(utils)/use-render/page.mdx))',
      '',
      DO_NOT_EDIT_MARKER,
      '',
      '## Details',
      '',
      '### useRender',
      '',
      'Render prop helper.',
      '',
      '## Stray note',
      '',
      'Some prose a human added.',
      '',
    ].join('\n');

    const parsed = await markdownToMetadata(markdown);
    // The wrapper title is still "Details", and the page kept its description.
    expect(parsed?.detailsSectionTitle).toBe('Details');
    expect(parsed?.pages[0]?.description).toBe('Render prop helper.');
  });

  it('defaults detailsSectionTitle so cache matches a fresh parse on first flat→grouped sync', async () => {
    // A previously flat index (no "## Details" wrapper) whose pages first gain route groups.
    const existingFlat = metadataToMarkdown(
      {
        title: 'React',
        pages: [
          { slug: 'intro', path: './intro/page.mdx', title: 'Intro', description: 'Intro page.' },
        ],
      },
      { path: 'src/app/react/page.mdx' },
    );

    const { metadata } = await mergeMetadataPages(existingFlat, {
      title: 'React',
      pages: [
        {
          slug: 'accordion',
          path: './(components)/accordion/page.mdx',
          title: 'Accordion',
          description: 'An accordion.',
        },
      ],
    });

    // The merged (cache) metadata carries the default wrapper title the renderer will write,
    // so a warm-cache read and a fresh parse of the written file agree.
    expect(metadata.sections).toEqual([{ title: 'Components' }]);
    expect(metadata.detailsSectionTitle).toBe('Details');

    const reparsed = await markdownToMetadata(
      metadataToMarkdown(metadata, { path: 'src/app/react/page.mdx' }),
    );
    expect(reparsed?.detailsSectionTitle).toBe('Details');
  });
});

// This helper is the single source of a page's index path, shared by both index
// producers (the remark metadata transform and the types loader). If they disagree on
// the path format, the types-loader write overwrites the remark's grouped index with a
// flat one — so keeping the route-group segment here is what makes grouping trigger.
describe('indexRelativePagePath', () => {
  it('keeps the route-group segment while resolving the parent past route groups', () => {
    expect(indexRelativePagePath('/app/react/(components)/accordion', 'page.mdx')).toBe(
      './(components)/accordion/page.mdx',
    );
  });

  it('preserves multiple consecutive route groups', () => {
    expect(indexRelativePagePath('/app/react/(components)/(inputs)/checkbox', 'page.mdx')).toBe(
      './(components)/(inputs)/checkbox/page.mdx',
    );
  });

  it('produces a flat path when there is no route group', () => {
    expect(indexRelativePagePath('/app/react/button', 'page.mdx')).toBe('./button/page.mdx');
  });
});

// A route-group path contains parentheses, which prettier normalizes by wrapping the link
// destination in angle brackets. The renderer must emit that same form so the generated file
// stays byte-stable when prettier formats it afterwards.
describe('route-group link destinations stay stable under prettier', () => {
  it('wraps a path containing parentheses in angle brackets, leaving flat paths untouched', () => {
    expect(formatLinkUrl('./(handbook)/styling/page.mdx')).toBe('<./(handbook)/styling/page.mdx>');
    expect(formatLinkUrl('./styling/page.mdx')).toBe('./styling/page.mdx');
    expect(formatLinkUrl('#styling')).toBe('#styling');
  });

  it('renders grouped Contents links angle-bracketed and round-trips back to the bare path', async () => {
    const data: PagesMetadata = {
      title: 'React',
      sections: [{ title: 'Handbook' }],
      pages: [
        {
          slug: 'styling',
          path: './(handbook)/styling/page.mdx',
          title: 'Styling',
          description: 'Style your components.',
          sectionIndex: 0,
        },
      ],
    };

    const markdown = metadataToMarkdown(data, { path: 'src/app/react/page.mdx' });

    // Both the editable list link and the Details "Read more" link are wrapped.
    expect(markdown).toContain('[Contents](<./(handbook)/styling/page.mdx>)');
    expect(markdown).toContain('[Read more](<./(handbook)/styling/page.mdx>)');

    // The mdast parser strips the angle brackets, so the recovered path is unchanged and
    // re-rendering is stable.
    const parsed = await markdownToMetadata(markdown);
    expect(parsed?.pages[0].path).toBe('./(handbook)/styling/page.mdx');
    expect(metadataToMarkdown(parsed!, { path: 'src/app/react/page.mdx' })).toBe(markdown);
  });
});

// A page's placement is its position under a heading, not a route group. A link with no route
// group of its own — an external link like /llms.txt — stays under whichever header a human
// filed it under, instead of falling back to the top of the index on the next regeneration.
describe('ungrouped links keep their manual section placement', () => {
  const grouped = (pages: PagesMetadata['pages']): PagesMetadata => ({
    title: 'React',
    sections: [{ title: 'Handbook' }],
    pages,
  });

  const sliceHandbook = (markdown: string) =>
    markdown.slice(markdown.indexOf('## Handbook'), markdown.indexOf('DO NOT EDIT'));

  const stylingPage: PagesMetadata['pages'][number] = {
    slug: 'styling',
    path: './(handbook)/styling/page.mdx',
    title: 'Styling',
    description: 'Style your components.',
    sectionIndex: 0,
  };
  const llmsPage = (sectionIndex?: number): PagesMetadata['pages'][number] => ({
    slug: 'llms',
    path: '/llms.txt',
    title: 'llms.txt',
    tags: ['External'],
    skipDetailSection: true,
    ...(sectionIndex !== undefined ? { sectionIndex } : {}),
  });

  it('renders an ungrouped page under the section named by its sectionIndex', () => {
    const markdown = metadataToMarkdown(grouped([stylingPage, llmsPage(0)]), {
      path: 'src/app/react/page.mdx',
    });

    // The external link sits inside the Handbook section, not ahead of the first heading.
    expect(sliceHandbook(markdown)).toContain('- [llms.txt](/llms.txt) [External]');
    expect(markdown.indexOf('## Handbook')).toBeLessThan(markdown.indexOf('/llms.txt'));
  });

  it('leaves a truly ungrouped page (no sectionIndex) ahead of the first heading', () => {
    const markdown = metadataToMarkdown(grouped([stylingPage, llmsPage()]), {
      path: 'src/app/react/page.mdx',
    });

    // With no remembered placement, the external link stays at the top (before Handbook).
    expect(markdown.indexOf('/llms.txt')).toBeLessThan(markdown.indexOf('## Handbook'));
  });

  it('parses the placement back and keeps it stable across a regeneration', async () => {
    const markdown = metadataToMarkdown(grouped([stylingPage, llmsPage(0)]), {
      path: 'src/app/react/page.mdx',
    });

    // The parser recovers which header the external link was filed under...
    const parsed = await markdownToMetadata(markdown);
    const llms = parsed?.pages.find((page) => page.path === '/llms.txt');
    expect(llms?.sectionIndex).toBe(0);

    // ...and re-rendering keeps it under Handbook (byte-stable round-trip).
    expect(metadataToMarkdown(parsed!, { path: 'src/app/react/page.mdx' })).toBe(markdown);
  });
});

// `syncPageIndex` pre-populates its page-index cache from the merged metadata, then asserts a
// warm read equals a fresh parse of the rendered file. The renderer clusters pages by section,
// so the merged metadata must already be in that order and carry the same detailsSectionTitle.
describe('merged grouped metadata matches a fresh parse (cache consistency)', () => {
  const interleaved: PagesMetadata = {
    title: 'React',
    pages: [
      { slug: 'a', path: './(g1)/a/page.mdx', title: 'A', description: 'A.' },
      { slug: 'b', path: './(g2)/b/page.mdx', title: 'B', description: 'B.' },
      { slug: 'c', path: './(g1)/c/page.mdx', title: 'C', description: 'C.' },
    ],
  };

  it('clusters merge-order pages into section order so warm and cold reads agree', async () => {
    const { metadata } = await mergeMetadataPages(undefined, interleaved);

    // Input interleaves g1, g2, g1; the cache metadata is re-ordered to the clustered order
    // the renderer emits (g1 pages, then g2), so it matches a fresh parse of the file.
    expect(metadata.pages.map((page) => page.slug)).toEqual(['a', 'c', 'b']);
    const fresh = await markdownToMetadata(
      metadataToMarkdown(metadata, { path: 'src/app/react/page.mdx' }),
    );
    expect(fresh?.pages.map((page) => page.path)).toEqual(metadata.pages.map((page) => page.path));
  });

  it('defaults detailsSectionTitle on a first-ever grouped sync', async () => {
    const { metadata } = await mergeMetadataPages(undefined, interleaved);
    expect(metadata.detailsSectionTitle).toBe('Details');

    const fresh = await markdownToMetadata(
      metadataToMarkdown(metadata, { path: 'src/app/react/page.mdx' }),
    );
    expect(fresh?.detailsSectionTitle).toBe('Details');
  });
});

// The resolver behind a page's search/sitemap `section` facet, shared by both producers
// (enrichPageIndex and transformMarkdownMetadata), so they resolve a page's section identically.
describe('createPageSectionResolver', () => {
  const resolveSection = createPageSectionResolver([{ title: 'Handbook' }, { title: 'Utilities' }]);

  it('resolves a page by its section index', () => {
    expect(resolveSection(0)).toBe('Handbook');
    expect(resolveSection(1)).toBe('Utilities');
  });

  it('returns undefined for an ungrouped page (no section index)', () => {
    expect(resolveSection()).toBeUndefined();
  });

  it('returns undefined for an out-of-range index', () => {
    expect(resolveSection(5)).toBeUndefined();
  });
});
