import {
  markdownToMetadata,
  metadataToMarkdown,
  orderPagesBySection,
  routeGroupOfPath,
  routeGroupToTitle,
  DEFAULT_DETAILS_SECTION_TITLE,
} from './metadataToMarkdown';
import type {
  MetadataToMarkdownOptions,
  PagesMetadata,
  PageMetadata,
  PageIndexSection,
} from './metadataToMarkdown';

/**
 * Derives the ordered route-group sections for an index, given the sections recovered
 * from the existing file (whose titles/order humans may have edited) and the per-page
 * section groups (each page's own route group, falling back to the group a human filed an
 * ungrouped page under). Existing sections are kept in place so renames and reordering
 * survive; a group seen for the first time is appended with a seeded title. Sections whose
 * last page has gone — including a section left holding only a manually-placed ungrouped
 * link — are kept as long as some page still references the group; a section no page
 * references is dropped. Returns undefined when no page has a group at all (flat index).
 */
function deriveIndexSections(
  existingSections: PageIndexSection[] | undefined,
  pageGroups: (string | undefined)[],
): PageIndexSection[] | undefined {
  const usedGroups = new Set(pageGroups.filter((group) => group !== undefined));

  const result: PageIndexSection[] = [];
  const seen = new Set<string>();

  // Keep existing sections (order + human-edited titles), de-duped by group and limited
  // to groups still in use.
  for (const section of existingSections ?? []) {
    if (usedGroups.has(section.group) && !seen.has(section.group)) {
      seen.add(section.group);
      result.push(section);
    }
  }

  // Append a seeded section for any in-use group not already covered, in page order.
  for (const group of pageGroups) {
    if (group && !seen.has(group)) {
      seen.add(group);
      result.push({ group, title: routeGroupToTitle(group) });
    }
  }

  return result.length > 0 ? result : undefined;
}

/**
 * Derives the grouped fields of a metadata result — sections, the canonically-ordered pages,
 * and the "Details" wrapper title — from a base set of sections/pages. Pages are reordered
 * into the section-clustered order the renderer emits, and `detailsSectionTitle` defaults to
 * the value the renderer would write, so the pre-populated cache matches a fresh parse of the
 * rendered file on every path (first sync, parse failure, and normal merge alike).
 */
function deriveGroupedFields(
  baseSections: PageIndexSection[] | undefined,
  pages: PageMetadata[],
  existingDetailsSectionTitle: string | undefined,
): Pick<PagesMetadata, 'pages' | 'sections' | 'detailsSectionTitle'> {
  // Each page's section group — its own route group, else the group a human filed it under —
  // computed once and reused for both deriving the sections and clustering the pages, so the
  // sync path parses each path only a single time.
  const pageGroups = pages.map((page) => routeGroupOfPath(page.path) ?? page.sectionGroup);
  const sections = deriveIndexSections(baseSections, pageGroups);
  return {
    sections,
    pages: sections ? orderPagesBySection(pages, sections, pageGroups) : pages,
    detailsSectionTitle: sections
      ? (existingDetailsSectionTitle ?? DEFAULT_DETAILS_SECTION_TITLE)
      : undefined,
  };
}

/**
 * Options for mergeMetadataMarkdown
 */
export interface MergeMetadataMarkdownOptions extends Omit<
  MetadataToMarkdownOptions,
  'editableMarker' | 'indexWrapperComponent'
> {
  /** If true, pages in existing markdown that aren't in newMetadata will be preserved. If false (default), they are removed. */
  preserveUnlisted?: boolean;
  /**
   * Component name to wrap the autogenerated content.
   * - `undefined`: preserve existing wrapper (if any)
   * - `null`: explicitly remove the wrapper
   * - `string`: use this component name
   */
  indexWrapperComponent?: string | null;
  /**
   * The path to the file being generated. Used in autogenerated comments to help
   * users validate the file.
   */
  path?: string;
  /**
   * If true, preserve existing page titles and slugs when they exist.
   * New metadata titles/slugs will only be used if the existing page doesn't have them.
   * Useful when auto-generating metadata that shouldn't override user-set values.
   * Default: false (new metadata takes precedence)
   */
  preserveExistingTitleAndSlug?: boolean;
}

/**
 * Result of merging new metadata into existing markdown: the normalized
 * `PagesMetadata` that renders to the merged markdown, plus the rendering options
 * needed to reproduce that markdown.
 */
export interface MergedMetadataResult {
  /** The normalized pages metadata that renders to the merged markdown. */
  metadata: PagesMetadata;
  /** Effective wrapper component to render with (undefined = no wrapper). */
  indexWrapperComponent?: string;
  /** Editable marker to render with (e.g. the alphabetical-sort marker), if any. */
  editableMarker?: string;
}

/**
 * Merges new page metadata with existing markdown content and returns the
 * normalized `PagesMetadata` (and rendering options) without serializing to markdown.
 *
 * This is the in-memory source of truth that {@link mergeMetadataMarkdown} renders.
 * `syncPageIndex` reuses it to pre-populate the page-index cache, so the cached
 * value matches a fresh read of the rendered markdown.
 *
 * See {@link mergeMetadataMarkdown} for the ordering and merge semantics.
 */
export async function mergeMetadataPages(
  existingMarkdown: string | undefined,
  newMetadata: PagesMetadata,
  options: MergeMetadataMarkdownOptions = {},
): Promise<MergedMetadataResult> {
  const { indexWrapperComponent, preserveExistingTitleAndSlug } = options;

  // With no existing markdown (or if it fails to parse), just use the new metadata. Use the
  // provided wrapper unless it's null (which means remove).
  const existingMetadata = existingMarkdown
    ? await markdownToMetadata(existingMarkdown)
    : undefined;
  if (!existingMetadata) {
    return {
      metadata: {
        ...newMetadata,
        ...deriveGroupedFields(
          newMetadata.sections,
          newMetadata.pages,
          newMetadata.detailsSectionTitle,
        ),
      },
      indexWrapperComponent: indexWrapperComponent === null ? undefined : indexWrapperComponent,
    };
  }

  // Determine effective wrapper component:
  // - undefined: preserve existing
  // - null: explicitly remove
  // - string: use provided value
  let effectiveWrapper: string | undefined;
  if (indexWrapperComponent === undefined) {
    effectiveWrapper = existingMetadata.indexWrapperComponent;
  } else if (indexWrapperComponent === null) {
    effectiveWrapper = undefined;
  } else {
    effectiveWrapper = indexWrapperComponent;
  }

  // Create a map of new pages by path for quick lookup
  const newPagesMap = new Map<string, PageMetadata>();
  for (const page of newMetadata.pages) {
    newPagesMap.set(page.path, page);
  }

  // Build the merged pages array, preserving order from existing markdown
  let pages: PageMetadata[] = [];
  const addedPaths = new Set<string>();

  // First, add all pages that exist in the existing markdown, in their original order
  for (const existingPage of existingMetadata.pages) {
    const newPage = newPagesMap.get(existingPage.path);
    if (newPage) {
      // Page exists in both - merge the metadata
      // Only exclude descriptionMarkdown if newPage provides a new description
      const { descriptionMarkdown, ...existingPageWithoutDescriptionMarkdown } = existingPage;
      const merged = {
        ...(newPage.description ? existingPageWithoutDescriptionMarkdown : existingPage),
        ...newPage,
        // Optionally preserve title/slug from existing (for auto-generated metadata that shouldn't override)
        ...(preserveExistingTitleAndSlug
          ? {
              title: existingPage.title || newPage.title,
              slug: existingPage.slug || newPage.slug,
            }
          : {}),
        // Preserve tags from existing (user-managed, program should never delete tags)
        tags: existingPage.tags,
        // Preserve skipDetailSection from existing (user-managed for external links)
        skipDetailSection: existingPage.skipDetailSection,
        // Preserve the section a human filed this page under (user-managed placement for
        // pages without a route group of their own, e.g. external links).
        sectionGroup: existingPage.sectionGroup,
        // Preserve sections from existing if new doesn't have them
        sections: newPage.sections || existingPage.sections,
        // Preserve displayTitle (user-managed title override) only if it still
        // differs from the new title. If the override now matches the actual title,
        // clear it so the titles stay in sync going forward.
        displayTitle:
          existingPage.displayTitle && existingPage.displayTitle !== newPage.title
            ? existingPage.displayTitle
            : undefined,
      };
      pages.push(merged);
      addedPaths.add(newPage.path);
    }
    // If page doesn't exist in new metadata, it's been removed - don't include it
  }

  // Then, add any new pages that weren't in the existing markdown
  for (const newPage of newMetadata.pages) {
    if (!addedPaths.has(newPage.path)) {
      // This is a new page - automatically add the [New] tag
      const pageWithTag = {
        ...newPage,
        tags: newPage.tags ? [...newPage.tags, 'New'] : ['New'],
      };
      pages.push(pageWithTag);
      addedPaths.add(newPage.path);
    }
  }

  // If alphabetical sorting is requested, sort pages alphabetically by title
  const alphabeticalSortMarker =
    "[//]: # 'This section is autogenerated, but the following list order, title, and [Tag]s can be modified, but nothing within the parentheses. Automatically sorted alphabetically.'";
  // TODO: Remove the old marker check once all index files have been migrated to the new format.
  const oldAlphabeticalSortMarker =
    "[//]: # 'This file is autogenerated, but the following list can be modified. Automatically sorted alphabetically.'";
  const requestsAlphabeticalSort =
    existingMarkdown?.includes(alphabeticalSortMarker) ||
    existingMarkdown?.includes(oldAlphabeticalSortMarker) ||
    false;

  if (requestsAlphabeticalSort) {
    pages = pages.sort((a, b) => {
      const titleA = a.displayTitle ?? a.title ?? a.slug;
      const titleB = b.displayTitle ?? b.title ?? b.slug;
      return titleA.localeCompare(titleB);
    });
  }

  // Preserve route-group section headings (order + human-edited titles) from the existing
  // file, appending sections for any newly-seen group; reorder pages into the section-
  // clustered order the renderer emits; and keep the "Details" wrapper heading, falling back
  // to the renderer's default when a flat index first becomes grouped — so the pre-populated
  // cache stays consistent with a fresh parse.
  const mergedMetadata: PagesMetadata = {
    title: newMetadata.title, // Always use the new title
    ...deriveGroupedFields(existingMetadata.sections, pages, existingMetadata.detailsSectionTitle),
    // Preserve the existing pageMetadata (e.g., robots config) from the current file
    pageMetadata: existingMetadata.pageMetadata,
  };

  return {
    metadata: mergedMetadata,
    indexWrapperComponent: effectiveWrapper,
    // Preserve the alphabetical sorting marker if it was present
    editableMarker: requestsAlphabeticalSort ? alphabeticalSortMarker : undefined,
  };
}

/**
 * Merges new page metadata with existing markdown content, preserving the order
 * of pages from the existing markdown when available, unless the file contains
 * only the autogeneration marker (no editable section), in which case pages are
 * sorted alphabetically by title.
 *
 * Pages are matched by their `path` property (e.g., './button/page.mdx'), not by slug.
 * This allows multiple pages to have the same slug (anchor) while still being treated
 * as distinct pages.
 *
 * @param existingMarkdown - The existing markdown content (or undefined if none exists)
 * @param newMetadata - The new metadata to merge in
 * @param options - Optional configuration
 * @param options.preserveUnlisted - If true, pages in existing markdown that aren't in newMetadata will be preserved. If false (default), they are removed.
 * @param options.indexWrapperComponent - Optional component name to wrap the autogenerated content (e.g., 'PagesIndex')
 * @returns The updated markdown content with merged metadata
 *
 * @example
 * ```ts
 * const existingMarkdown = `# Components
 * - Button - ([Outline](#button), [Contents](./button/page.mdx)) - A button
 * - Checkbox - ([Outline](#checkbox), [Contents](./checkbox/page.mdx)) - A checkbox
 * `;
 *
 * const newMetadata = {
 *   title: 'Components',
 *   pages: [
 *     { slug: 'checkbox', path: './checkbox/page.mdx', title: 'Checkbox', description: 'Updated checkbox' },
 *     { slug: 'button', path: './button/page.mdx', title: 'Button', description: 'Updated button' },
 *     { slug: 'input', path: './input/page.mdx', title: 'Input', description: 'New input' },
 *   ],
 * };
 *
 * const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);
 * // Result preserves Button, Checkbox order from existing markdown, adds Input at the end
 * ```
 */
export async function mergeMetadataMarkdown(
  existingMarkdown: string | undefined,
  newMetadata: PagesMetadata,
  options: MergeMetadataMarkdownOptions = {},
): Promise<string> {
  const { path } = options;
  const { metadata, indexWrapperComponent, editableMarker } = await mergeMetadataPages(
    existingMarkdown,
    newMetadata,
    options,
  );
  return metadataToMarkdown(metadata, { editableMarker, indexWrapperComponent, path });
}
