import { describe, it, expect } from 'vitest';
import { mergeMetadataMarkdown } from './mergeMetadataMarkdown';
import type { PagesMetadata } from './metadataToMarkdown';

describe('mergeMetadataMarkdown', () => {
  it('should create new markdown when no existing markdown is provided', async () => {
    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(undefined, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should preserve order from existing markdown', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Checkbox

Old checkbox description.

[Read more](./checkbox/page.mdx)

## Button

Old button description.

[Read more](./button/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'Updated button description.',
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'Updated checkbox description.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
      - [Button](#button) - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Checkbox

      Updated checkbox description.

      [Read more](./checkbox/page.mdx)

      ## Button

      Updated button description.

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should add new pages at the end while preserving existing order', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)
- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old button description.

[Read more](./button/page.mdx)

## Checkbox

Old checkbox description.

[Read more](./checkbox/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'A checkbox component.',
        },
        {
          slug: 'input',
          path: './input/page.mdx',
          title: 'Input',
          description: 'An input component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) - [Full Docs](./button/page.mdx)
      - [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
      - [Input](#input) [New] - [Full Docs](./input/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      ## Checkbox

      A checkbox component.

      [Read more](./checkbox/page.mdx)

      ## Input

      An input component.

      [Read more](./input/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should remove pages that are not in new metadata', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)
- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
- [Input](#input) - [Full Docs](./input/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old button description.

[Read more](./button/page.mdx)

## Checkbox

Old checkbox description.

[Read more](./checkbox/page.mdx)

## Input

Old input description.

[Read more](./input/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'A checkbox component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) - [Full Docs](./button/page.mdx)
      - [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      ## Checkbox

      A checkbox component.

      [Read more](./checkbox/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should update title from new metadata', async () => {
    const existingMarkdown = `# Old Title

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old button description.

[Read more](./button/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'New Title',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# New Title

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should handle malformed markdown by using new metadata only', async () => {
    const existingMarkdown = `This is not valid markdown`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should update all metadata fields while preserving order', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old description.

[Read more](./button/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'New description with more details.',
          keywords: ['interactive', 'input'],
          openGraph: {
            title: 'Button Component',
            description: 'A comprehensive button component.',
            images: [
              {
                url: 'https://example.com/button.png',
                width: 800,
                height: 600,
                alt: 'Button preview',
              },
            ],
          },
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button Component](#button) - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button Component

      A comprehensive button component.

      ![Button preview](https://example.com/button.png)

      <details>

      <summary>Outline</summary>

      - Keywords: interactive, input

      </details>

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should handle empty existing pages array', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'A button component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Button](#button) [New] - [Full Docs](./button/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Button

      A button component.

      [Read more](./button/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should handle complex reordering scenario', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)
- [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)
- [Middle](#middle) - [Full Docs](./middle/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Zebra

Old Z description.

[Read more](./zebra/page.mdx)

## Alpha

Old A description.

[Read more](./alpha/page.mdx)

## Middle

Old M description.

[Read more](./middle/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        // Pages in alphabetical order (different from existing)
        {
          slug: 'alpha',
          path: './alpha/page.mdx',
          title: 'Alpha',
          description: 'Updated A.',
        },
        {
          slug: 'beta',
          path: './beta/page.mdx',
          title: 'Beta',
          description: 'New B.',
        },
        {
          slug: 'middle',
          path: './middle/page.mdx',
          title: 'Middle',
          description: 'Updated M.',
        },
        {
          slug: 'zebra',
          path: './zebra/page.mdx',
          title: 'Zebra',
          description: 'Updated Z.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)
      - [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)
      - [Middle](#middle) - [Full Docs](./middle/page.mdx)
      - [Beta](#beta) [New] - [Full Docs](./beta/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Zebra

      Updated Z.

      [Read more](./zebra/page.mdx)

      ## Alpha

      Updated A.

      [Read more](./alpha/page.mdx)

      ## Middle

      Updated M.

      [Read more](./middle/page.mdx)

      ## Beta

      New B.

      [Read more](./beta/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should fix inconsistent ordering in input markdown', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
- [Button](#button) - [Full Docs](./button/page.mdx)
- [Input](#input) - [Full Docs](./input/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

Old button description.

[Read more](./button/page.mdx)

## Input

Old input description.

[Read more](./input/page.mdx)

## Checkbox

Old checkbox description.

[Read more](./checkbox/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'button',
          path: './button/page.mdx',
          title: 'Button',
          description: 'Updated button.',
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'Updated checkbox.',
        },
        {
          slug: 'input',
          path: './input/page.mdx',
          title: 'Input',
          description: 'Updated input.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)
      - [Button](#button) - [Full Docs](./button/page.mdx)
      - [Input](#input) - [Full Docs](./input/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Checkbox

      Updated checkbox.

      [Read more](./checkbox/page.mdx)

      ## Button

      Updated button.

      [Read more](./button/page.mdx)

      ## Input

      Updated input.

      [Read more](./input/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should handle metadata with parts, props, dataAttributes, and cssVariables', async () => {
    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'tooltip',
          path: './tooltip/page.mdx',
          title: 'Tooltip',
          description: 'A tooltip component.',
          parts: {
            Root: {
              props: ['className'],
            },
            Trigger: {
              props: ['align'],
            },
            Popup: {
              props: ['defaultOpen', 'open', 'side'],
              dataAttributes: ['data-align', 'data-open', 'data-side'],
              cssVariables: ['--anchor-height', '--anchor-width', '--transform-origin'],
            },
            Portal: {},
          },
        },
      ],
    };

    const result = await mergeMetadataMarkdown(undefined, newMetadata);

    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Tooltip](#tooltip) - [Full Docs](./tooltip/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Tooltip

      A tooltip component.

      <details>

      <summary>Outline</summary>

      - Exports:
        - Tooltip - Root
          - Props: className
        - Tooltip - Trigger
          - Props: align
        - Tooltip - Popup
          - Props: defaultOpen, open, side
          - Data Attributes: data-align, data-open, data-side
          - CSS Variables: --anchor-height, --anchor-width, --transform-origin
        - Tooltip - Portal

      </details>

      [Read more](./tooltip/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should round-trip parse metadata with all new fields', async () => {
    const originalMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'alert-dialog',
          path: './alert-dialog/page.mdx',
          title: 'Alert Dialog',
          description: 'An alert dialog component.',
          exports: {
            Root: {
              props: ['className'],
            },
            Trigger: {
              props: ['defaultOpen', 'modal', 'onOpenChange', 'open'],
              dataAttributes: ['data-open', 'data-closed'],
            },
            Popup: {
              cssVariables: ['--popup-height', '--popup-width'],
            },
            Backdrop: {},
          },
        },
      ],
    };

    const markdown = await mergeMetadataMarkdown(undefined, originalMetadata);

    // Now parse it back
    const { markdownToMetadata } = await import('./metadataToMarkdown');
    const parsedMetadata = await markdownToMetadata(markdown);

    expect(parsedMetadata).not.toBeNull();
    expect(parsedMetadata?.title).toBe('Components');
    expect(parsedMetadata?.pages).toHaveLength(1);

    const page = parsedMetadata?.pages[0];
    expect(page?.slug).toBe('alert-dialog');
    expect(page?.title).toBe('Alert Dialog');
    expect(page?.description).toBe('An alert dialog component.');
    expect(page?.exports).toEqual({
      Root: {
        props: ['className'],
      },
      Trigger: {
        props: ['defaultOpen', 'modal', 'onOpenChange', 'open'],
        dataAttributes: ['data-open', 'data-closed'],
      },
      Popup: {
        cssVariables: ['--popup-height', '--popup-width'],
      },
      Backdrop: {},
    });
  });

  it('should update existing page when title changes instead of creating duplicate', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Old Button Name](#old-button-name) - [Full Docs](./button/page.mdx)
- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Old Button Name

Old description of the button.

[Read more](./button/page.mdx)

## Checkbox

A checkbox component.

[Read more](./checkbox/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'new-button-name',
          path: './button/page.mdx',
          title: 'New Button Name',
          description: 'Updated description of the button.',
        },
        {
          slug: 'checkbox',
          path: './checkbox/page.mdx',
          title: 'Checkbox',
          description: 'A checkbox component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    // Should update the existing entry's title in both TOC and content section,
    // and use the NEW description from the metadata (not preserve the old one)
    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [New Button Name](#new-button-name) - [Full Docs](./button/page.mdx)
      - [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## New Button Name

      Updated description of the button.

      [Read more](./button/page.mdx)

      ## Checkbox

      A checkbox component.

      [Read more](./checkbox/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should preserve order when file has no alphabetical sorting marker', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)
- [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Zebra

Z component.

[Read more](./zebra/page.mdx)

## Alpha

A component.

[Read more](./alpha/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'zebra',
          path: './zebra/page.mdx',
          title: 'Zebra',
          description: 'Z component.',
        },
        {
          slug: 'alpha',
          path: './alpha/page.mdx',
          title: 'Alpha',
          description: 'A component.',
        },
        {
          slug: 'middle',
          path: './middle/page.mdx',
          title: 'Middle',
          description: 'M component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    // Should preserve Zebra, Alpha order and add Middle at the end
    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified.'

      - [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)
      - [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)
      - [Middle](#middle) [New] - [Full Docs](./middle/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Zebra

      Z component.

      [Read more](./zebra/page.mdx)

      ## Alpha

      A component.

      [Read more](./alpha/page.mdx)

      ## Middle

      M component.

      [Read more](./middle/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  it('should sort pages alphabetically when file requests alphabetical sorting', async () => {
    const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified. Automatically sorted alphabetically.'

- [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)
- [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Zebra

Z component.

[Read more](./zebra/page.mdx)

## Alpha

A component.

[Read more](./alpha/page.mdx)
`;

    const newMetadata: PagesMetadata = {
      title: 'Components',
      pages: [
        {
          slug: 'zebra',
          path: './zebra/page.mdx',
          title: 'Zebra',
          description: 'Z component.',
        },
        {
          slug: 'alpha',
          path: './alpha/page.mdx',
          title: 'Alpha',
          description: 'A component.',
        },
        {
          slug: 'middle',
          path: './middle/page.mdx',
          title: 'Middle',
          description: 'M component.',
        },
      ],
    };

    const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

    // Should sort alphabetically with explicit marker preserved
    expect(result).toMatchInlineSnapshot(`
      "# Components

      [//]: # 'This file is autogenerated, but the following list can be modified. Automatically sorted alphabetically.'

      - [Alpha](#alpha) - [Full Docs](./alpha/page.mdx)
      - [Middle](#middle) [New] - [Full Docs](./middle/page.mdx)
      - [Zebra](#zebra) - [Full Docs](./zebra/page.mdx)

      [//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

      ## Alpha

      A component.

      [Read more](./alpha/page.mdx)

      ## Middle

      M component.

      [Read more](./middle/page.mdx)

      ## Zebra

      Z component.

      [Read more](./zebra/page.mdx)

      [//]: # 'This file is autogenerated, but the following metadata can be modified.'

      export const metadata = {
        robots: {
          index: false,
        },
      };
      "
    `);
  });

  describe('tags handling', () => {
    it('should preserve existing tags when merging', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) [Hot] - [Full Docs](./button/page.mdx)
- [Checkbox](#checkbox) [Beta] - [Full Docs](./checkbox/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

## Checkbox

A checkbox component.

[Read more](./checkbox/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
          {
            slug: 'checkbox',
            path: './checkbox/page.mdx',
            title: 'Checkbox',
            description: 'Updated checkbox description.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // Tags should be preserved
      expect(result).toContain('- [Button](#button) [Hot] - [Full Docs](./button/page.mdx)');
      expect(result).toContain('- [Checkbox](#checkbox) [Beta] - [Full Docs](./checkbox/page.mdx)');
    });

    it('should automatically add [New] tag to new entries', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'A button component.',
          },
          {
            slug: 'checkbox',
            path: './checkbox/page.mdx',
            title: 'Checkbox',
            description: 'A new checkbox component.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // Existing entry should not have [New] tag
      expect(result).toContain('- [Button](#button) - [Full Docs](./button/page.mdx)\n');
      // New entry should automatically get [New] tag
      expect(result).toContain('- [Checkbox](#checkbox) [New] - [Full Docs](./checkbox/page.mdx)');
    });

    it('should preserve multiple tags', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) [New] [Hot] [Beta] - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // All tags should be preserved
      expect(result).toContain(
        '- [Button](#button) [New] [Hot] [Beta] - [Full Docs](./button/page.mdx)',
      );
    });

    it('should handle mix of entries with and without tags', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) [Hot] - [Full Docs](./button/page.mdx)
- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

## Checkbox

A checkbox component.

[Read more](./checkbox/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'A button component.',
          },
          {
            slug: 'checkbox',
            path: './checkbox/page.mdx',
            title: 'Checkbox',
            description: 'A checkbox component.',
          },
          {
            slug: 'input',
            path: './input/page.mdx',
            title: 'Input',
            description: 'A new input component.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // Button should keep its [Hot] tag
      expect(result).toContain('- [Button](#button) [Hot] - [Full Docs](./button/page.mdx)');
      // Checkbox should remain without tags
      expect(result).toContain('- [Checkbox](#checkbox) - [Full Docs](./checkbox/page.mdx)\n');
      // Input (new entry) should get [New] tag
      expect(result).toContain('- [Input](#input) [New] - [Full Docs](./input/page.mdx)');
    });

    it('should not duplicate [New] tag if already present', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) [New] - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'A button component.',
          },
          {
            slug: 'checkbox',
            path: './checkbox/page.mdx',
            title: 'Checkbox',
            description: 'A new checkbox component.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // Button should keep its single [New] tag (not duplicated)
      expect(result).toContain('- [Button](#button) [New] - [Full Docs](./button/page.mdx)\n');
      // Checkbox should get [New] tag
      expect(result).toContain('- [Checkbox](#checkbox) [New] - [Full Docs](./checkbox/page.mdx)');
    });

    it('should preserve skipDetailSection flag from existing markdown', async () => {
      const existingMarkdown = `# Handbook

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Forms](#forms) - [Full Docs](./forms/page.mdx)
- [llms.txt](/llms.txt) [External]
- [TypeScript](#typescript) - [Full Docs](./typescript/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Forms

A guide to building forms.

[Read more](./forms/page.mdx)

## TypeScript

A guide to using TypeScript.

[Read more](./typescript/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Handbook',
        pages: [
          {
            slug: 'forms',
            path: './forms/page.mdx',
            title: 'Forms',
            description: 'Updated forms guide.',
          },
          {
            slug: 'llms-txt',
            path: '/llms.txt',
            title: 'llms.txt',
            description: 'No description available',
          },
          {
            slug: 'typescript',
            path: './typescript/page.mdx',
            title: 'TypeScript',
            description: 'Updated TypeScript guide.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // llms.txt should preserve its skipDetailSection flag and [External] tag
      expect(result).toContain('- [llms.txt](/llms.txt) [External]');
      // llms.txt should NOT have a detail section
      expect(result).not.toContain('## llms.txt');
      // Regular entries should still have detail sections
      expect(result).toContain('## Forms');
      expect(result).toContain('## TypeScript');
    });

    it('should preserve skipDetailSection with tags for single-link entries', async () => {
      const existingMarkdown = `# Resources

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [API](/api) [External] [New]
- [Documentation](#docs) - [Full Docs](./docs/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Documentation

Internal documentation.

[Read more](./docs/page.mdx)
`;

      const newMetadata: PagesMetadata = {
        title: 'Resources',
        pages: [
          {
            slug: 'api',
            path: '/api',
            title: 'API',
            description: 'No description available',
          },
          {
            slug: 'docs',
            path: './docs/page.mdx',
            title: 'Documentation',
            description: 'Internal documentation.',
          },
        ],
      };

      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      // API should preserve both tags and skipDetailSection
      expect(result).toContain('- [API](/api) [External] [New]');
      // API should NOT have a detail section
      expect(result).not.toContain('## API');
      // Documentation should have detail section
      expect(result).toContain('## Documentation');
    });
  });

  describe('indexWrapperComponent handling', () => {
    it('should preserve existing wrapper when indexWrapperComponent is undefined', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

<PagesIndex>

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

</PagesIndex>

[//]: # 'This file is autogenerated, but the following metadata can be modified.'

export const metadata = {
  robots: {
    index: false,
  },
};
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      // No indexWrapperComponent option passed - should preserve existing
      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      expect(result).toContain('<PagesIndex>');
      expect(result).toContain('</PagesIndex>');
    });

    it('should remove wrapper when indexWrapperComponent is null', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

<PagesIndex>

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

</PagesIndex>

[//]: # 'This file is autogenerated, but the following metadata can be modified.'

export const metadata = {
  robots: {
    index: false,
  },
};
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      // Explicitly pass null to remove wrapper
      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata, {
        indexWrapperComponent: null,
      });

      expect(result).not.toContain('<PagesIndex>');
      expect(result).not.toContain('</PagesIndex>');
    });

    it('should use new wrapper when indexWrapperComponent is a string', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

<PagesIndex>

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

</PagesIndex>

[//]: # 'This file is autogenerated, but the following metadata can be modified.'

export const metadata = {
  robots: {
    index: false,
  },
};
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      // Explicitly set a new wrapper
      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata, {
        indexWrapperComponent: 'ComponentsIndex',
      });

      expect(result).not.toContain('<PagesIndex>');
      expect(result).toContain('<ComponentsIndex>');
      expect(result).toContain('</ComponentsIndex>');
    });

    it('should add wrapper when existing markdown has none and indexWrapperComponent is provided', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

[//]: # 'This file is autogenerated, but the following metadata can be modified.'

export const metadata = {
  robots: {
    index: false,
  },
};
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      // Add a wrapper to markdown that doesn't have one
      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata, {
        indexWrapperComponent: 'PagesIndex',
      });

      expect(result).toContain('<PagesIndex>');
      expect(result).toContain('</PagesIndex>');
    });

    it('should not add wrapper when existing markdown has none and indexWrapperComponent is undefined', async () => {
      const existingMarkdown = `# Components

[//]: # 'This file is autogenerated, but the following list can be modified.'

- [Button](#button) - [Full Docs](./button/page.mdx)

[//]: # 'This file is autogenerated, DO NOT EDIT AFTER THIS LINE'

## Button

A button component.

[Read more](./button/page.mdx)

[//]: # 'This file is autogenerated, but the following metadata can be modified.'

export const metadata = {
  robots: {
    index: false,
  },
};
`;

      const newMetadata: PagesMetadata = {
        title: 'Components',
        pages: [
          {
            slug: 'button',
            path: './button/page.mdx',
            title: 'Button',
            description: 'Updated button description.',
          },
        ],
      };

      // No option passed - should preserve lack of wrapper
      const result = await mergeMetadataMarkdown(existingMarkdown, newMetadata);

      expect(result).not.toContain('<PagesIndex>');
      expect(result).not.toContain('</PagesIndex>');
    });
  });
});
