import { unified } from 'unified';
import remarkParse from 'remark-parse';
import { visit } from 'unist-util-visit';
import type { Heading, Paragraph, Image, Link, Root, Code } from 'mdast';
import type { ExtractedMetadata, HeadingHierarchy } from '../transformMarkdownMetadata/types';
import { heading, paragraph, text, link, comment } from './createMarkdownNodes';
import { isRouteGroup, routeGroupName } from '../loaderUtils/stripRouteGroups';
import type { Audience, PageIndexSection } from '../../createSitemap/types';

export type { PageIndexSection };

/** Default heading for the detail-region wrapper of a grouped index. */
export const DEFAULT_DETAILS_SECTION_TITLE = 'Details';

/**
 * Escapes underscores in a string for markdown compatibility.
 * Prevents underscores from being interpreted as emphasis markers.
 * @example escapeUnderscores('_options') -> '\_options'
 */
function escapeUnderscores(str: string): string {
  return str.replace(/_/g, '\\_');
}

/**
 * Unescapes underscores in a string that was escaped for markdown.
 * @example unescapeUnderscores('\_options') -> '_options'
 */
function unescapeUnderscores(str: string): string {
  return str.replace(/\\_/g, '_');
}

type HeadingNode = Heading;
type ParagraphNode = Paragraph;
type ImageNode = Image;
type LinkNode = Link;
type CodeNode = Code;

// Definition nodes are used for markdown-style comments like [//]: # "Comment text"
interface DefinitionNode {
  type: 'definition';
  identifier: string;
  label: string;
  title?: string;
  url: string;
}

/**
 * Serializes a URL for a markdown link destination. A URL containing parentheses (such as a
 * Next.js route group like `./(handbook)/styling/page.mdx`) or whitespace is wrapped in angle
 * brackets, matching how prettier normalizes it — so the generated file stays stable when
 * prettier formats it afterwards. The mdast parser reads the angle-bracketed form back to the
 * same URL, so the round-trip is unaffected.
 */
export function formatLinkUrl(url: string): string {
  return /[\s()]/.test(url) ? `<${url}>` : url;
}

/**
 * Converts AST nodes (from heading.children) back to markdown string
 */
function astNodesToMarkdown(nodes: any[]): string {
  let result = '';
  for (const node of nodes) {
    if (node.type === 'text') {
      result += node.value;
    } else if (node.type === 'inlineCode') {
      result += `\`${node.value}\``;
    } else if (node.type === 'emphasis') {
      // Prettier serializes emphasis with underscores; match it to keep the
      // generated file stable when prettier formats it afterwards.
      result += `_${astNodesToMarkdown(node.children)}_`;
    } else if (node.type === 'strong') {
      result += `**${astNodesToMarkdown(node.children)}**`;
    } else if (node.type === 'link') {
      result += `[${astNodesToMarkdown(node.children)}](${formatLinkUrl(node.url)})`;
    } else if ('children' in node) {
      result += astNodesToMarkdown(node.children);
    }
  }
  return result;
}

export interface PageMetadata extends ExtractedMetadata {
  /** The slug/path for this page (e.g., 'button', 'checkbox') */
  slug: string;
  /** The relative path to the page's MDX file */
  path: string;
  /**
   * User-customized display title for the page.
   * When set, this overrides `title` in the navigation list and sitemap.
   * The `title` field continues to be used for the heading section.
   *
   * This value is detected automatically: if a user edits the list item text
   * so it no longer matches the heading, the edited text is preserved here.
   */
  displayTitle?: string;
  /** Tags for this entry (e.g., 'New', 'Hot', 'Beta') */
  tags?: string[];
  /** Skip generating detail section for this entry (for external links) */
  skipDetailSection?: boolean;
  /**
   * The route group of the index section this page is manually filed under, in a grouped
   * index. Only meaningful for a page whose own path has no route group (e.g. an external
   * link like `/llms.txt`): it can't derive a section from its path, so this remembers the
   * header a human placed it under and keeps it there across regenerations. Route-grouped
   * pages ignore this — they always sort into the section matching their path's group.
   */
  sectionGroup?: string;
  /**
   * The intended audience for this page.
   * When omitted, the page is public and intended for all audiences.
   */
  audience?: Audience;
  /** Whether this page is an index page (has the autogenerated comment marker) */
  index?: boolean;
  /** Component parts with their API metadata (for multi-part components) */
  parts?: Record<
    string,
    {
      props?: string[];
      dataAttributes?: string[];
      cssVariables?: string[];
      /** For hooks and functions: parameter names.
       * Each element is a string (positional param) or string[] (object param keys). */
      parameters?: (string | string[])[];
      /** For hooks and functions: return value keys (if returns an object) */
      returns?: string[];
    }
  >;
  /** Component exports with their API metadata (used for both single and multi-part components) */
  exports?: Record<
    string,
    {
      /** For components: prop names */
      props?: string[];
      /** For components: data attribute names */
      dataAttributes?: string[];
      /** For components: CSS variable names */
      cssVariables?: string[];
      /** For hooks and functions: parameter names.
       * Each element is a string (positional param) or string[] (object param keys). */
      parameters?: (string | string[])[];
      /** For hooks and functions: return value keys (if returns an object) */
      returns?: string[];
    }
  >;
  /** Type names documented on this page (state objects, enums, type aliases, etc.) */
  types?: string[];
}

export interface PagesMetadata {
  /** The main title for the pages index */
  title: string;
  /** Description below the title (editable, persisted) */
  description?: string;
  /** Array of page metadata */
  pages: PageMetadata[];
  /**
   * Ordered section headings for the editable link region, present when the index is
   * organized by Next.js route group. Each entry maps a route group to the
   * (human-editable) heading its pages are listed under; the array order is the order
   * the sections appear in the file.
   *
   * When omitted, the index renders as a single flat list (the pre-existing behavior).
   * A page whose route group (from its path) matches no section — or that has no group —
   * is listed ungrouped ahead of the first section heading.
   */
  sections?: PageIndexSection[];
  /**
   * Heading text for the H2 that wraps the detail region when the index is grouped
   * (see {@link sections}). Defaults to {@link DEFAULT_DETAILS_SECTION_TITLE}. Only used
   * in grouped mode; a flat index renders its per-page details directly as H2 with no wrapper.
   */
  detailsSectionTitle?: string;
  /** Page-level metadata for export (e.g., robots, etc.) */
  pageMetadata?: Record<string, unknown>;
  /** Name of a React component that wraps the autogenerated index content */
  indexWrapperComponent?: string;
}

/**
 * Resolves the page metadata embedded in an autogenerated index, falling back to
 * the default (private, non-indexed) metadata when none is provided.
 *
 * Shared between rendering (`metadataToMarkdownAst`) and cache pre-population in
 * `syncPageIndex` so the cached read-model matches a fresh parse of the rendered file.
 */
export function resolveIndexPageMetadata(
  pageMetadata?: Record<string, unknown>,
): Record<string, unknown> {
  if (pageMetadata && Object.keys(pageMetadata).length > 0) {
    return pageMetadata;
  }
  return { robots: { index: false }, other: { audience: 'private' } };
}

/**
 * Collapses runs of whitespace to single spaces and trims, the way the parser normalizes
 * paragraph text. Shared so cache pre-population (which builds the read-model from in-memory
 * metadata) produces the same description/title strings a fresh parse of the markdown would.
 */
export function collapseInlineWhitespace(text: string): string {
  return text.replace(/[ \t\n\r]+/g, ' ').trim();
}

/**
 * Options for metadataToMarkdown and metadataToMarkdownAst functions
 */
export interface MetadataToMarkdownOptions {
  /**
   * Custom editable section marker comment.
   * If not provided, uses the default marker.
   */
  editableMarker?: string;
  /**
   * Name of a React component to wrap around the autogenerated index content.
   * If provided, the generated markdown will wrap the page list and detail sections
   * in this component (e.g., `<PagesIndex>...</PagesIndex>`).
   * @example 'PagesIndex'
   */
  indexWrapperComponent?: string;
  /**
   * The path to the file being generated. Used in autogenerated comments to help
   * users validate the file.
   */
  path?: string;
}

/**
 * Serializes a JS value to a JavaScript-style literal string (unquoted keys, trailing commas).
 * This produces output like `{ robots: { index: false } }` instead of JSON's `{ "robots": { "index": false } }`.
 */
function serializeJsValue(value: unknown, indent: number): string {
  if (value === null || value === undefined) {
    return String(value);
  }
  if (typeof value === 'string') {
    // Use single quotes for strings, escaping any internal single quotes
    return `'${String(value).replace(/'/g, "\\'")}'`;
  }
  if (typeof value !== 'object') {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }
    const items = value.map(
      (item) => `${'  '.repeat(indent + 1)}${serializeJsValue(item, indent + 1)},`,
    );
    return `[\n${items.join('\n')}\n${'  '.repeat(indent)}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length === 0) {
    return '{}';
  }
  const lines = entries.map(
    ([key, val]) => `${'  '.repeat(indent + 1)}${key}: ${serializeJsValue(val, indent + 1)},`,
  );
  return `{\n${lines.join('\n')}\n${'  '.repeat(indent)}}`;
}

/**
 * Gets the status label for a page based on its audience and index flags.
 *
 * Status labels in the editable list:
 * - \"Private\": audience='private', index=false
 * - \"Index\": audience='private', index=true
 * - \"Public Index\": audience!='private', index=true
 * - \"Introductory\": audience='introductory'
 * - \"Intermediate\": audience='intermediate'
 * - \"Advanced\": audience='advanced'
 * - \"Business\": audience='business'
 */
function getStatusLabel(page: PageMetadata): string | undefined {
  const audience = page.audience;
  const isIndex = page.index ?? false;

  if (audience === 'private' && isIndex) {
    return 'Index';
  }
  if (audience === 'private' && !isIndex) {
    return 'Private';
  }
  if (audience && audience !== 'private' && isIndex) {
    const audienceLabel = audience.charAt(0).toUpperCase() + audience.slice(1);
    return `${audienceLabel} Index`;
  }
  if (audience && audience !== 'private') {
    return audience.charAt(0).toUpperCase() + audience.slice(1);
  }
  if (isIndex) {
    return 'Public Index';
  }
  return undefined;
}

/**
 * Parses a status label string back into audience/index flags.
 */
function parseStatusLabel(label: string): { audience?: Audience; index: boolean } {
  const trimmed = label.trim();
  switch (trimmed) {
    case 'Private':
      return { audience: 'private', index: false };
    case 'Index':
      return { audience: 'private', index: true };
    case 'Public Index':
      return { index: true };
    case 'Introductory':
      return { audience: 'introductory', index: false };
    case 'Introductory Index':
      return { audience: 'introductory', index: true };
    case 'Intermediate':
      return { audience: 'intermediate', index: false };
    case 'Intermediate Index':
      return { audience: 'intermediate', index: true };
    case 'Advanced':
      return { audience: 'advanced', index: false };
    case 'Advanced Index':
      return { audience: 'advanced', index: true };
    case 'Business':
      return { audience: 'business', index: false };
    case 'Business Index':
      return { audience: 'business', index: true };
    default:
      throw new Error(
        `Unknown status label "${trimmed}". ` +
          'Valid labels are: Private, Index, Public Index, Introductory, Introductory Index, ' +
          'Intermediate, Intermediate Index, Advanced, Advanced Index, Business, Business Index.',
      );
  }
}

/**
 * Converts a HeadingHierarchy into markdown list format
 */
function headingHierarchyToMarkdown(
  hierarchy: HeadingHierarchy,
  basePath: string,
  depth: number = 0,
): string {
  let result = '';
  const indent = '  '.repeat(depth);

  for (const node of Object.values(hierarchy)) {
    const { titleMarkdown, children } = node;
    // Convert AST nodes back to markdown string with preserved formatting
    let titleString = astNodesToMarkdown(titleMarkdown);

    // Escape numbered list syntax (e.g., "1. Text" -> "1\. Text")
    // This prevents markdown from treating "- 1. Text" as a nested ordered list
    titleString = titleString.replace(/^(\d+)\.\s/, '$1\\. ');

    result += `${indent}- ${titleString}\n`;
    if (Object.keys(children).length > 0) {
      result += headingHierarchyToMarkdown(children, basePath, depth + 1);
    }
  }

  return result;
}

/**
 * Converts a HeadingHierarchy into markdown AST list nodes
 */
function headingHierarchyToListNodes(hierarchy: HeadingHierarchy, basePath: string): any[] {
  const listItems: any[] = [];

  for (const node of Object.values(hierarchy)) {
    const { titleMarkdown, children } = node;

    const listItem: any = {
      type: 'listItem',
      children: [
        {
          type: 'paragraph',
          children: titleMarkdown, // Use the preserved AST nodes directly
        },
      ],
    };

    // Add nested children if they exist
    if (Object.keys(children).length > 0) {
      const nestedList = {
        type: 'list',
        ordered: false,
        children: headingHierarchyToListNodes(children, basePath),
      };
      listItem.children.push(nestedList);
    }

    listItems.push(listItem);
  }

  return listItems;
}

/**
 * Strips position metadata from AST nodes recursively
 */
function stripPositions(nodes: any[]): any[] {
  return nodes.map((node) => {
    const { position, ...rest } = node;
    if (rest.children) {
      rest.children = stripPositions(rest.children);
    }
    return rest;
  });
}

/**
 * Parses exports metadata from a nested list structure
 * Expects format:
 * - Exports:
 *   - ComponentName - PartName
 *     - Props: a, b, c
 *     - Parameters: x, y (for hooks/functions)
 *     - Returns: ReturnType (for hooks/functions)
 *     - Data Attributes: x, y
 *     - CSS Variables: --var1, --var2
 */
function parseExportsFromListItem(listItem: any): {
  exports?: PageMetadata['exports'];
  parts?: PageMetadata['parts'];
} {
  const exports: PageMetadata['exports'] = {};
  const parts: PageMetadata['parts'] = {};

  // Find the nested list within this list item
  const nestedList = listItem.children?.find((child: any) => child.type === 'list');

  if (!nestedList?.children) {
    return { exports };
  }

  // Parse each export/part item from the nested list
  for (const exportListItem of nestedList.children) {
    if (exportListItem.type !== 'listItem') {
      continue;
    }

    // Find the paragraph with the export/part name
    const exportParagraph = exportListItem.children?.find(
      (child: any) => child.type === 'paragraph',
    );
    if (!exportParagraph) {
      continue;
    }

    // Extract the name from the text node
    const textNode = exportParagraph.children?.find((child: any) => child.type === 'text');
    if (!textNode) {
      continue;
    }

    const fullName = textNode.value || '';

    // Check if this is a part (has dash) or export (no dash)
    const hasDash = fullName.includes(' - ');

    // Find the nested list with props/dataAttributes/cssVariables
    const metadataList = exportListItem.children?.find((child: any) => child.type === 'list');

    // Initialize the metadata (only add properties that have content)
    const metadata: {
      props?: string[];
      dataAttributes?: string[];
      cssVariables?: string[];
      parameters?: (string | string[])[];
      returns?: string[];
    } = {};

    if (metadataList) {
      // Parse each metadata item
      for (const metadataItem of metadataList.children) {
        if (metadataItem.type !== 'listItem') {
          continue;
        }

        const metadataParagraph = metadataItem.children?.find(
          (child: any) => child.type === 'paragraph',
        );
        if (!metadataParagraph) {
          continue;
        }

        const metadataText = extractPlainTextFromNode(metadataParagraph);

        if (metadataText.startsWith('Props:')) {
          const propsText = metadataText.replace('Props:', '').trim();
          if (propsText) {
            metadata.props = propsText.split(',').map((p) => unescapeUnderscores(p.trim()));
          }
        } else if (metadataText.startsWith('Parameters:')) {
          const parametersText = metadataText.replace('Parameters:', '').trim();
          if (parametersText) {
            // When parameters are wrapped in ( ), they represent properties of a
            // single object parameter. Store as a nested string[] element.
            const objectMatch = parametersText.match(/^\((.+)\)$/);
            if (objectMatch) {
              const inner = objectMatch[1].trim();
              const keys = inner.split(',').map((p) => unescapeUnderscores(p.trim()));
              metadata.parameters = [keys];
            } else {
              metadata.parameters = parametersText
                .split(',')
                .map((p) => unescapeUnderscores(p.trim()));
            }
          }
        } else if (metadataText.startsWith('Data Attributes:')) {
          const dataAttributesText = metadataText.replace('Data Attributes:', '').trim();
          if (dataAttributesText) {
            metadata.dataAttributes = dataAttributesText
              .split(',')
              .map((attr) => unescapeUnderscores(attr.trim()));
          }
        } else if (metadataText.startsWith('CSS Variables:')) {
          const cssVariablesText = metadataText.replace('CSS Variables:', '').trim();
          if (cssVariablesText) {
            metadata.cssVariables = cssVariablesText
              .split(',')
              .map((cssVar) => unescapeUnderscores(cssVar.trim()));
          }
        } else if (metadataText.startsWith('Returns:')) {
          const returnsText = metadataText.replace('Returns:', '').trim();
          if (returnsText) {
            metadata.returns = returnsText.split(',').map((r) => unescapeUnderscores(r.trim()));
          }
        }
      }
    }

    if (hasDash) {
      // This is a part name (e.g., "ComponentName - PartName")
      const partName = fullName.split(' - ').pop() || fullName;
      // Always add the part, even if it has no properties
      parts[partName] = metadata;
    } else {
      // This is an export name (no dash)
      const exportName = fullName;
      // Always add the export, even if it has no properties
      exports[exportName] = metadata;
    }
  }

  return {
    exports: Object.keys(exports).length > 0 ? exports : undefined,
    parts: Object.keys(parts).length > 0 ? parts : undefined,
  };
}

/**
 * Parses a list of section links back into a HeadingHierarchy structure
 * Expects list items with links in the format: [Title](path#slug)
 * OR plain text in the format: Title
 */
function parseHeadingSections(listNode: any): HeadingHierarchy {
  const hierarchy: HeadingHierarchy = {};
  const stack: Array<{ depth: number; node: HeadingHierarchy }> = [{ depth: -1, node: hierarchy }];

  // Helper to calculate depth from list nesting
  function processListItems(
    items: any[],
    baseDepth: number,
    parentIsOrdered: boolean = false,
    startIndex: number = 1,
  ) {
    for (let i = 0; i < items.length; i += 1) {
      const item = items[i];
      if (item.type !== 'listItem') {
        continue;
      }

      // Find the paragraph content
      const itemParagraph = item.children?.find((child: any) => child.type === 'paragraph');
      if (!itemParagraph) {
        continue;
      }

      // Try to find a link first (linked format)
      const itemLink = itemParagraph?.children?.find((child: any) => child.type === 'link');

      let title = '';
      let titleMarkdown: any[] = [];
      let slug = '';

      if (itemLink) {
        // Linked format: [Title](path#slug)
        title = itemLink.children?.[0]?.value || '';
        // Strip position metadata from titleMarkdown
        titleMarkdown = stripPositions(itemLink.children || []);
        const url = itemLink.url || '';
        slug = url.split('#')[1] || '';
      } else {
        // Plain text format: extract all children (preserves formatting)
        // Strip position metadata from titleMarkdown
        titleMarkdown = stripPositions(itemParagraph.children || []);

        // Extract plain text for slug generation
        let rawTitle = itemParagraph.children
          .map((child: any) => {
            if (child.type === 'text') {
              return child.value;
            }
            if (child.type === 'inlineCode') {
              return child.value;
            }
            if ('children' in child) {
              // Recursively extract text from nested nodes
              return astNodesToMarkdown(child.children).replace(/[*`_]/g, '');
            }
            return '';
          })
          .join('')
          .trim();

        // Unescape numbered list syntax (e.g., "1\. Text" -> "1. Text")
        // This handles titles that were escaped during serialization
        rawTitle = rawTitle.replace(/^(\d+)\\\.\s/, '$1. ');

        // If this is from an ordered list, prepend the number
        if (parentIsOrdered) {
          const itemNumber = startIndex + i;
          title = `${itemNumber}. ${rawTitle}`;
          // Update titleMarkdown to include the number
          titleMarkdown = [{ type: 'text', value: title }];
        } else {
          title = rawTitle;
        }

        // Generate slug from the title (with number if applicable)
        slug = title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '');
      }

      if (title && slug && titleMarkdown.length > 0) {
        // Pop stack until we find the parent at the right depth
        while (stack.length > 0 && stack[stack.length - 1].depth >= baseDepth) {
          stack.pop();
        }

        const parent = stack[stack.length - 1].node;
        const newNode = {
          title,
          titleMarkdown,
          children: {} as HeadingHierarchy,
        };
        parent[slug] = newNode;
        stack.push({ depth: baseDepth, node: newNode.children });

        // Check for nested lists (can be ordered or unordered)
        const nestedLists = item.children?.filter((child: any) => child.type === 'list');
        for (const nestedList of nestedLists || []) {
          if (nestedList.children) {
            const nestedIsOrdered = nestedList.ordered === true;
            const nestedStart = nestedList.start || 1;
            // Always increment depth for true nesting
            processListItems(nestedList.children, baseDepth + 1, nestedIsOrdered, nestedStart);
          }
        }
      }
    }
  }

  if (listNode?.type === 'list' && listNode.children) {
    processListItems(listNode.children, 0);
  }

  return hierarchy;
} /**
 * Converts an array of page metadata into a markdown AST
 */
export function metadataToMarkdownAst(
  data: PagesMetadata,
  options: MetadataToMarkdownOptions = {},
): Root {
  const { editableMarker, indexWrapperComponent, path } = options;
  const { title: mainTitle, description: mainDescription, pages, pageMetadata } = data;
  const children: Root['children'] = [];

  // Add main title
  children.push(heading(1, mainTitle));

  // Add description if provided (editable section)
  if (mainDescription) {
    children.push(paragraph(mainDescription));
  }

  // Add editable section marker
  // Extract just the comment text from the marker (strip [//]: # 'text' wrapper)
  const defaultMarkerText =
    'This section is autogenerated, but the following list order, title, and [Tag]s can be modified, but nothing within the parentheses.';
  let markerText = defaultMarkerText;
  if (editableMarker) {
    // Extract text between single quotes: [//]: # 'text'
    const match = editableMarker.match(/\[\/\/\]: # '(.+)'/);
    markerText = match ? match[1] : defaultMarkerText;
  }
  children.push(comment(markerText) as any);

  // Open wrapper component if provided
  if (indexWrapperComponent) {
    children.push({
      type: 'html',
      value: `<${indexWrapperComponent}>`,
    } as any);
  }

  // Add page list (editable section) as proper list items
  const listItems: any[] = [];
  for (const page of pages) {
    // List items use displayTitle when the user has overridden the title
    const listTitle = page.displayTitle ?? page.title ?? page.slug;

    // Check if this is a single-link entry (external link or no detail section)
    const isSingleLink = page.skipDetailSection || false;

    let paragraphChildren: any[];
    if (isSingleLink) {
      // Format: - [Title](./path) [Tag1] [Tag2]
      paragraphChildren = [link(page.path, listTitle)];

      // Add tags if present (directly after link)
      if (page.tags && page.tags.length > 0) {
        for (const tag of page.tags) {
          paragraphChildren.push(text(` [${tag}]`));
        }
      }
    } else {
      // Format: - Title [Tag1] [Tag2] - (StatusLabel, [Outline](#slug), [Contents](./path))
      const statusLabel = getStatusLabel(page);
      paragraphChildren = [text(listTitle)];

      // Add tags if present (directly after component name)
      if (page.tags && page.tags.length > 0) {
        for (const tag of page.tags) {
          paragraphChildren.push(text(` [${tag}]`));
        }
      }

      // Add separator and parenthetical links (status label first if present)
      paragraphChildren.push(text(statusLabel ? ` - (${statusLabel}, ` : ' - ('));
      paragraphChildren.push(link(`#${page.slug}`, 'Outline'));
      paragraphChildren.push(text(', '));
      paragraphChildren.push(link(page.path, 'Contents'));
      paragraphChildren.push(text(')'));
    }

    listItems.push({
      type: 'listItem',
      spread: false,
      children: [paragraph(paragraphChildren)],
    });
  }

  // Add the list to children
  children.push({
    type: 'list',
    ordered: false,
    spread: false,
    children: listItems,
  } as any);

  // Add non-editable section marker
  // Trim common prefixes and suffixes from path, quote if contains parentheses for shell safety
  const normalizedPath = typeof path === 'string' ? path.replace(/\\/g, '/') : undefined;
  const trimmedPath = normalizedPath
    ?.replace(/^(src\/app\/|app\/)/, '')
    .replace(/\/page\.mdx$/, '');
  const quotedPath = trimmedPath && /[()]/.test(trimmedPath) ? `"${trimmedPath}"` : trimmedPath;
  const doNotEditComment = quotedPath
    ? `This section is autogenerated, DO NOT EDIT AFTER THIS LINE, run: pnpm docs:validate ${quotedPath}`
    : 'This section is autogenerated, DO NOT EDIT AFTER THIS LINE';
  children.push(comment(doNotEditComment) as any);

  // Add detailed page sections (non-editable)
  for (const page of pages) {
    const pageTitle = page.title || page.slug;
    // Note: We don't replace newlines here to allow natural line breaks in detailed sections
    const description = page.description || 'No description available';
    const keywords = page.keywords || [];
    const image = page.image;

    // Add page heading
    children.push(heading(2, pageTitle));

    // Add description
    children.push(paragraph(description));

    // Add image if available
    if (image) {
      children.push({
        type: 'paragraph',
        children: [
          {
            type: 'image',
            url: image.url,
            alt: image.alt || pageTitle,
          },
        ],
      } as any);
    }

    // Add metadata list (keywords, sections, parts, and exports combined)
    const hasKeywords = keywords.length > 0;
    const hasSections = page.sections && Object.keys(page.sections).length > 0;
    const hasParts = page.parts && Object.keys(page.parts).length > 0;
    const hasExports = page.exports && Object.keys(page.exports).length > 0;
    const hasTypes = page.types && page.types.length > 0;

    if (hasKeywords || hasSections || hasParts || hasExports || hasTypes) {
      const metadataListItems: any[] = [];

      if (hasKeywords) {
        metadataListItems.push({
          type: 'listItem',
          children: [paragraph(`Keywords: ${keywords.join(', ')}`)],
        });
      }

      if (hasSections && page.sections) {
        const sectionListItems = headingHierarchyToListNodes(page.sections, page.path);
        metadataListItems.push({
          type: 'listItem',
          children: [
            paragraph('Sections:'),
            {
              type: 'list',
              ordered: false,
              children: sectionListItems,
            },
          ],
        });
      }

      if (hasParts || hasExports) {
        const exportsListItems: any[] = [];

        // First, add all parts with their metadata (use dash format)
        if (hasParts && page.parts) {
          for (const [partName, partMetadata] of Object.entries(page.parts)) {
            const partListItems: any[] = [];

            if (partMetadata.props && partMetadata.props.length > 0) {
              partListItems.push({
                type: 'listItem',
                children: [
                  paragraph(`Props: ${partMetadata.props.map(escapeUnderscores).join(', ')}`),
                ],
              });
            }

            if (partMetadata.dataAttributes && partMetadata.dataAttributes.length > 0) {
              partListItems.push({
                type: 'listItem',
                children: [
                  paragraph(
                    `Data Attributes: ${partMetadata.dataAttributes.map(escapeUnderscores).join(', ')}`,
                  ),
                ],
              });
            }

            if (partMetadata.cssVariables && partMetadata.cssVariables.length > 0) {
              partListItems.push({
                type: 'listItem',
                children: [
                  paragraph(
                    `CSS Variables: ${partMetadata.cssVariables.map(escapeUnderscores).join(', ')}`,
                  ),
                ],
              });
            }

            if (partMetadata.parameters && partMetadata.parameters.length > 0) {
              const paramsText = partMetadata.parameters
                .map((p) =>
                  Array.isArray(p)
                    ? `(${p.map(escapeUnderscores).join(', ')})`
                    : escapeUnderscores(p),
                )
                .join(', ');
              partListItems.push({
                type: 'listItem',
                children: [paragraph(`Parameters: ${paramsText}`)],
              });
            }

            if (partMetadata.returns && partMetadata.returns.length > 0) {
              partListItems.push({
                type: 'listItem',
                children: [
                  paragraph(`Returns: ${partMetadata.returns.map(escapeUnderscores).join(', ')}`),
                ],
              });
            }

            // Add the part with dash separator
            if (partListItems.length > 0) {
              exportsListItems.push({
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [{ type: 'text', value: `${page.title} - ${partName}` }],
                  },
                  {
                    type: 'list',
                    ordered: false,
                    children: partListItems,
                  },
                ],
              });
            } else {
              // Part with no properties - just add the part name with dash
              exportsListItems.push({
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [{ type: 'text', value: `${page.title} - ${partName}` }],
                  },
                ],
              });
            }
          }
        }

        // Then add all exports with their metadata (no dash format)
        if (hasExports && page.exports) {
          for (const [exportName, exportMetadata] of Object.entries(page.exports)) {
            const exportListItems: any[] = [];

            if (exportMetadata.props && exportMetadata.props.length > 0) {
              exportListItems.push({
                type: 'listItem',
                children: [
                  paragraph(`Props: ${exportMetadata.props.map(escapeUnderscores).join(', ')}`),
                ],
              });
            }

            if (exportMetadata.parameters && exportMetadata.parameters.length > 0) {
              const paramsText = exportMetadata.parameters
                .map((p) =>
                  Array.isArray(p)
                    ? `(${p.map(escapeUnderscores).join(', ')})`
                    : escapeUnderscores(p),
                )
                .join(', ');
              exportListItems.push({
                type: 'listItem',
                children: [paragraph(`Parameters: ${paramsText}`)],
              });
            }

            if (exportMetadata.returns && exportMetadata.returns.length > 0) {
              exportListItems.push({
                type: 'listItem',
                children: [
                  paragraph(`Returns: ${exportMetadata.returns.map(escapeUnderscores).join(', ')}`),
                ],
              });
            }

            if (exportMetadata.dataAttributes && exportMetadata.dataAttributes.length > 0) {
              exportListItems.push({
                type: 'listItem',
                children: [
                  paragraph(
                    `Data Attributes: ${exportMetadata.dataAttributes.map(escapeUnderscores).join(', ')}`,
                  ),
                ],
              });
            }

            if (exportMetadata.cssVariables && exportMetadata.cssVariables.length > 0) {
              exportListItems.push({
                type: 'listItem',
                children: [
                  paragraph(
                    `CSS Variables: ${exportMetadata.cssVariables.map(escapeUnderscores).join(', ')}`,
                  ),
                ],
              });
            }

            // Always add the export, even if it has no properties
            if (exportListItems.length > 0) {
              exportsListItems.push({
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [{ type: 'text', value: exportName }],
                  },
                  {
                    type: 'list',
                    ordered: false,
                    children: exportListItems,
                  },
                ],
              });
            } else {
              // Export with no properties - just add the export name
              exportsListItems.push({
                type: 'listItem',
                children: [
                  {
                    type: 'paragraph',
                    children: [{ type: 'text', value: exportName }],
                  },
                ],
              });
            }
          }
        }

        if (exportsListItems.length > 0) {
          metadataListItems.push({
            type: 'listItem',
            children: [
              paragraph('Exports:'),
              {
                type: 'list',
                ordered: false,
                children: exportsListItems,
              },
            ],
          });
        }
      }

      if (hasTypes && page.types) {
        metadataListItems.push({
          type: 'listItem',
          children: [paragraph(`Types: ${page.types.join(', ')}`)],
        });
      }

      // Wrap metadata in details/summary tags
      children.push({
        type: 'html',
        value: '<details>',
      } as any);
      children.push(paragraph(''));
      children.push({
        type: 'html',
        value: '<summary>Outline</summary>',
      } as any);
      children.push(paragraph(''));
      children.push({
        type: 'list',
        ordered: false,
        children: metadataListItems,
      } as any);
      children.push(paragraph(''));
      children.push({
        type: 'html',
        value: '</details>',
      } as any);
    }

    // Add embeddings as a comment if available
    if (page.embeddings && page.embeddings.length > 0) {
      children.push(comment(`Embeddings: ${JSON.stringify(page.embeddings)}`));
    }

    // Add read more link
    children.push(paragraph([link(page.path, 'Read more')]));
  }

  // Add metadata marker (inside wrapper component if provided)
  children.push(
    comment(
      'The above section is autogenerated, but the remainder of the file can be modified.',
    ) as any,
  );

  // Close wrapper component if provided
  if (indexWrapperComponent) {
    children.push({
      type: 'html',
      value: `</${indexWrapperComponent}>`,
    } as any);
  }

  const metadataObj = resolveIndexPageMetadata(pageMetadata);
  const typeAnnotation =
    "/** @type {import('@mui/internal-docs-infra/createSitemap/types').NextMetadata} */";
  const metadataCode = `export const metadata =\n  ${typeAnnotation} (${serializeJsValue(metadataObj, 1)});`;
  // Output as raw MDX/JSX code (mdxjsEsm node type)
  children.push({
    type: 'mdxjsEsm',
    value: metadataCode,
  } as any);

  return {
    type: 'root',
    children,
  };
}

/**
 * Extracts the Next.js route group a page is organized under, from its relative path.
 *
 * A page listed in a grouped index bubbled up past a leading run of one or more route
 * groups; the outermost of those (the segment directly under the index's non-group
 * directory) is its section. When several route groups are consecutive, the outermost
 * wins and the inner ones are transparent to sectioning. A leading non-group segment
 * means the page has no section (it did not bubble past a group into this index).
 *
 * @example routeGroupOfPath('./(overview)/quick-start/page.mdx') -> '(overview)'
 * @example routeGroupOfPath('./(public)/(content)/react/page.mdx') -> '(public)'
 * @example routeGroupOfPath('./quick-start/page.mdx') -> undefined
 */
export function routeGroupOfPath(path: string): string | undefined {
  const firstSegment = path.replace(/^\.\//, '').split('/')[0];
  return firstSegment && isRouteGroup(firstSegment) ? firstSegment : undefined;
}

/**
 * The route-group section a page belongs to: its own route group, falling back to the group
 * a human filed it under (`sectionGroup`) for a page whose path has no route group (e.g. an
 * external link). This single expression must key every place that decides section membership
 * — {@link clusterPagesBySection}, the sitemap resolver, and the merge step's section
 * derivation — so a section is never dropped while a page still claims it.
 */
export function pageSectionGroup(page: PageMetadata): string | undefined {
  return routeGroupOfPath(page.path) ?? page.sectionGroup;
}

/**
 * A stable synthetic group id for an editable heading that has no route-grouped page under it
 * — e.g. an `## External Links` heading a human filled with only external links. Route groups
 * key a section to its pages via the page paths; a heading with no such page has nothing to key
 * it, so without an id the section would be dropped and its links would fall to the top of the
 * index on the next regeneration. The id is derived from the heading text so it is recovered
 * identically on every parse (a stable round-trip); renaming the heading yields a new id and its
 * links fall back to ungrouped. The `#` prefix namespaces it so it can never collide with a real
 * `(route-group)` key. Returns undefined for an empty/whitespace heading, which stays dropped.
 */
export function syntheticSectionGroup(title: string): string | undefined {
  const slug = titleToSlug(title);
  return slug ? `#${slug}` : undefined;
}

/**
 * The canonical route-group key for an editable section, from its (human-editable) title and the
 * paths of the pages listed under it, in order. A page's own route group wins — the first one
 * encountered. With none, a section holding only external links takes a stable
 * {@link syntheticSectionGroup} from its title, while a section holding any local tree page
 * (`./…`) stays flat (`undefined`) under route-group rules. A section with no pages is dropped
 * (`undefined`).
 *
 * This is the single rule the parser ({@link markdownToMetadata}) and the merge step's section
 * derivation share, so once a section's last route-grouped page is gone — leaving nothing in the
 * rendered file that still encodes the real group — the metadata a warm cache carries collapses to
 * the same synthetic id a fresh parse assigns, instead of clinging to the now-unrecoverable group.
 */
export function resolveSectionGroup(title: string, paths: string[]): string | undefined {
  let sawLocalPage = false;
  for (const path of paths) {
    const candidate = routeGroupOfPath(path);
    if (candidate) {
      return candidate;
    }
    if (path.startsWith('./')) {
      sawLocalPage = true;
    }
  }
  return paths.length > 0 && !sawLocalPage ? syntheticSectionGroup(title) : undefined;
}

/**
 * Whether any page renders a detail section, i.e. the grouped-index `## Details` wrapper (and its
 * `detailsSectionTitle`) exists. The renderer and the merge step both key off this — shared here
 * so the pre-populated cache can't claim a wrapper title the rendered file omits. Order-independent,
 * so a reordered detail list yields the same answer as the raw page list.
 */
export function hasDetailSection(pages: PageMetadata[]): boolean {
  return pages.some((page) => !page.skipDetailSection);
}

/**
 * Buckets pages into their index sections in canonical render order: the ungrouped pages
 * first, then each section in `sections` order, preserving input order within each bucket.
 * A page's section is its own route group, falling back to the group a human filed it under
 * (`sectionGroup`); a page matching no section is ungrouped. Shared by the renderer and the
 * merge step so the serialized file and the pre-populated cache agree on page order.
 */
export function clusterPagesBySection(
  pages: PageMetadata[],
  sections: PageIndexSection[],
  pageGroups?: (string | undefined)[],
): { ungrouped: PageMetadata[]; bySection: Map<string, PageMetadata[]> } {
  const bySection = new Map<string, PageMetadata[]>(sections.map((section) => [section.group, []]));
  const ungrouped: PageMetadata[] = [];
  pages.forEach((page, index) => {
    const group = pageGroups ? pageGroups[index] : pageSectionGroup(page);
    const bucket = (group && bySection.get(group)) || ungrouped;
    bucket.push(page);
  });
  return { ungrouped, bySection };
}

/**
 * Flattens {@link clusterPagesBySection} into the single canonical page order the renderer
 * emits (ungrouped first, then each section). Used to normalize a merged page list so a warm
 * cache matches a fresh parse of the rendered file. A flat index (no sections) is unchanged.
 * A precomputed `pageGroups` (aligned with `pages`) is threaded through to avoid recomputing.
 */
export function orderPagesBySection(
  pages: PageMetadata[],
  sections: PageIndexSection[],
  pageGroups?: (string | undefined)[],
): PageMetadata[] {
  const { ungrouped, bySection } = clusterPagesBySection(pages, sections, pageGroups);
  return [...ungrouped, ...sections.flatMap((section) => bySection.get(section.group) ?? [])];
}

/**
 * Seeds a human-readable section title from a route-group folder name. Used the first
 * time a group is encountered; the result is then free for humans to edit.
 *
 * @example routeGroupToTitle('(overview)') -> 'Overview'
 * @example routeGroupToTitle('(alert-dialog)') -> 'Alert Dialog'
 */
export function routeGroupToTitle(group: string): string {
  // Strip the surrounding parentheses via the shared route-group rule (a synthetic `#id` or other
  // non-group value is title-cased as-is), then split on word separators and capitalize.
  return (routeGroupName(group) ?? group)
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Builds a resolver from a page to its route-group section title, for the given index
 * sections. The section is taken from the page's own route group, falling back to the
 * group a human filed it under (`sectionGroup`) for a page whose path has no route group.
 * Returns undefined when neither yields a matching section. Shared by the sitemap producers
 * so a page's `section` resolves identically whichever pipeline builds the read-model.
 */
export function createPageSectionResolver(
  sections: PageIndexSection[] | undefined,
): (path: string, sectionGroup?: string) => string | undefined {
  const titleByGroup = new Map((sections ?? []).map((section) => [section.group, section.title]));
  return (path, sectionGroup) => {
    const group = routeGroupOfPath(path) ?? sectionGroup;
    return group ? titleByGroup.get(group) : undefined;
  };
}

/**
 * The heading depth of a per-page detail section. Grouped indexes nest details as H3
 * under a single `## Details` H2; flat indexes render them directly as H2. Shared by the
 * renderer and parser so the round-trip depth convention lives in one place.
 */
export function detailHeadingDepth(isGrouped: boolean): number {
  return isGrouped ? 3 : 2;
}

/**
 * Converts an array of page metadata into the markdown format (string)
 */
export function metadataToMarkdown(
  data: PagesMetadata,
  options: MetadataToMarkdownOptions | string = {},
): string {
  // Support legacy signature where second param was editableMarker string
  const normalizedOptions: MetadataToMarkdownOptions =
    typeof options === 'string' ? { editableMarker: options } : options;
  const { editableMarker, indexWrapperComponent, path } = normalizedOptions;

  const { title, description, pages, pageMetadata, sections, detailsSectionTitle } = data;
  const isGrouped = !!(sections && sections.length > 0);
  const lines: string[] = [];

  // Add main title
  lines.push(`# ${title}`);
  lines.push('');

  // Add description if provided (editable section)
  if (description) {
    lines.push(description);
    lines.push('');
  }

  // Add editable section marker
  const marker =
    editableMarker ??
    "[//]: # 'This section is autogenerated, but the following list order, title, and [Tag]s can be modified, but nothing within the parentheses.'";
  lines.push(marker);
  lines.push('');

  // Open wrapper component if provided
  if (indexWrapperComponent) {
    lines.push(`<${indexWrapperComponent}>`);
    lines.push('');
  }

  // Renders a single page's editable list line (shared by flat and grouped modes).
  const renderListLine = (page: PageMetadata): string => {
    // List items use displayTitle when the user has overridden the title
    const listTitle = page.displayTitle ?? page.title ?? page.slug;

    // Check if this is a single-link entry (external link or no detail section)
    const isSingleLink = page.skipDetailSection || false;

    if (isSingleLink) {
      // Format: - [Title](./path) [Tag1] [Tag2]
      let line = `- [${listTitle}](${formatLinkUrl(page.path)})`;
      if (page.tags && page.tags.length > 0) {
        for (const tag of page.tags) {
          line += ` [${tag}]`;
        }
      }
      return line;
    }

    // Format: - Title [Tag1] [Tag2] - (StatusLabel, [Outline](#slug), [Contents](./path))
    const statusLabel = getStatusLabel(page);
    let line = `- ${listTitle}`;
    if (page.tags && page.tags.length > 0) {
      for (const tag of page.tags) {
        line += ` [${tag}]`;
      }
    }
    line += statusLabel
      ? ` - (${statusLabel}, [Outline](#${page.slug}), [Contents](${formatLinkUrl(page.path)}))`
      : ` - ([Outline](#${page.slug}), [Contents](${formatLinkUrl(page.path)}))`;
    return line;
  };

  // In grouped mode, bucket pages into their sections (ungrouped first, then each section in
  // order). A page with no route group of its own falls back to the section a human filed it
  // under; one matching no section is ungrouped and listed ahead of the first heading.
  const { ungrouped, bySection } = isGrouped
    ? clusterPagesBySection(pages, sections!)
    : { ungrouped: [] as PageMetadata[], bySection: new Map<string, PageMetadata[]>() };

  // Add page list (editable section)
  if (isGrouped) {
    for (const page of ungrouped) {
      lines.push(renderListLine(page));
    }
    if (ungrouped.length > 0) {
      lines.push('');
    }
    sections!.forEach((section, sectionIndex) => {
      const depth = section.depth ?? 2;
      lines.push(`${'#'.repeat(depth)} ${section.title}`);
      lines.push('');
      for (const page of bySection.get(section.group) ?? []) {
        lines.push(renderListLine(page));
      }
      if (sectionIndex < sections!.length - 1) {
        lines.push('');
      }
    });
  } else {
    for (const page of pages) {
      lines.push(renderListLine(page));
    }
  }

  lines.push('');

  // Add non-editable section marker
  // Trim common prefixes and suffixes from path, quote if contains parentheses for shell safety
  const normalizedPath = typeof path === 'string' ? path.replace(/\\/g, '/') : undefined;
  const trimmedPath = normalizedPath
    ?.replace(/^(src\/app\/|app\/)/, '')
    .replace(/\/page\.mdx$/, '');
  const quotedPath = trimmedPath && /[()]/.test(trimmedPath) ? `"${trimmedPath}"` : trimmedPath;
  const doNotEditMarker = quotedPath
    ? `[//]: # 'This section is autogenerated, DO NOT EDIT AFTER THIS LINE, run: pnpm docs:validate ${quotedPath}'`
    : "[//]: # 'This section is autogenerated, DO NOT EDIT AFTER THIS LINE'";
  lines.push(doNotEditMarker);
  lines.push('');

  // In grouped mode, order the detail sections by section (ungrouped first, then each
  // section in order) and wrap them under a single "Details" H2 so they nest cleanly in
  // the outline instead of trailing under the last section heading. Flat mode is
  // unchanged: per-page details render directly as H2 in list order.
  const detailPages = isGrouped
    ? [...ungrouped, ...sections!.flatMap((section) => bySection.get(section.group) ?? [])]
    : pages;
  const detailHeadingPrefix = '#'.repeat(detailHeadingDepth(isGrouped));

  if (isGrouped && hasDetailSection(detailPages)) {
    lines.push(`## ${detailsSectionTitle ?? DEFAULT_DETAILS_SECTION_TITLE}`);
    lines.push('');
  }

  // Add detailed page sections (non-editable)
  for (const page of detailPages) {
    // Skip detail section for single-link entries (external links)
    if (page.skipDetailSection) {
      continue;
    }

    const pageTitle = page.title || page.slug;
    // Use descriptionMarkdown to preserve formatting if available
    // Note: We don't replace newlines here to allow natural line breaks in detailed sections
    let pageDescription: string;
    if (page.descriptionMarkdown && page.descriptionMarkdown.length > 0) {
      pageDescription = astNodesToMarkdown(page.descriptionMarkdown);
    } else {
      pageDescription = page.description || 'No description available';
    }
    const keywords = page.keywords || [];
    const image = page.image;

    // Add page heading
    lines.push(`${detailHeadingPrefix} ${pageTitle}`);
    lines.push('');

    // Add description
    lines.push(pageDescription);
    lines.push('');

    // Add image if available
    if (image) {
      lines.push(`![${image.alt || pageTitle}](${image.url})`);
      lines.push('');
    }

    // Add metadata list (keywords, sections, parts, and exports)
    const hasKeywords = keywords.length > 0;
    const hasSections = page.sections && Object.keys(page.sections).length > 0;
    const hasParts = page.parts && Object.keys(page.parts).length > 0;
    const hasExports = page.exports && Object.keys(page.exports).length > 0;
    const hasTypes = page.types && page.types.length > 0;

    // Track if we actually add any metadata content
    let hasMetadataContent = false;

    if (hasKeywords || hasSections || hasParts || hasExports || hasTypes) {
      lines.push('<details>');
      lines.push('');
      lines.push('<summary>Outline</summary>');
      lines.push('');
      if (hasKeywords) {
        lines.push(`- Keywords: ${keywords.join(', ')}`);
        hasMetadataContent = true;
      }
      if (hasSections && page.sections) {
        const sectionLines = headingHierarchyToMarkdown(page.sections, page.path, 1); // Start at depth 1 for indentation
        lines.push('- Sections:');
        lines.push(sectionLines.trimEnd());
        hasMetadataContent = true;
      }
      // Handle both parts and exports
      // Parts and exports are combined into a single "Exports:" section
      // Parts use format "ComponentName - PartName" (written with dash)
      // Exports use just "ExportName" (written without dash)
      if (hasParts || hasExports) {
        lines.push('- Exports:');

        // First, list all parts with their metadata (use dash format)
        if (hasParts && page.parts) {
          for (const [partName, partMetadata] of Object.entries(page.parts)) {
            const hasProps = partMetadata.props && partMetadata.props.length > 0;
            const hasDataAttributes =
              partMetadata.dataAttributes && partMetadata.dataAttributes.length > 0;
            const hasCssVariables =
              partMetadata.cssVariables && partMetadata.cssVariables.length > 0;
            const hasParameters = partMetadata.parameters && partMetadata.parameters.length > 0;

            lines.push(`  - ${page.title} - ${partName}`);

            if (hasProps) {
              lines.push(`    - Props: ${partMetadata.props!.map(escapeUnderscores).join(', ')}`);
            }
            if (hasDataAttributes) {
              lines.push(
                `    - Data Attributes: ${partMetadata.dataAttributes!.map(escapeUnderscores).join(', ')}`,
              );
            }
            if (hasCssVariables) {
              lines.push(
                `    - CSS Variables: ${partMetadata.cssVariables!.map(escapeUnderscores).join(', ')}`,
              );
            }
            if (hasParameters) {
              const paramsText = partMetadata
                .parameters!.map((p) =>
                  Array.isArray(p)
                    ? `(${p.map(escapeUnderscores).join(', ')})`
                    : escapeUnderscores(p),
                )
                .join(', ');
              lines.push(`    - Parameters: ${paramsText}`);
            }
            if (partMetadata.returns && partMetadata.returns.length > 0) {
              lines.push(
                `    - Returns: ${partMetadata.returns.map(escapeUnderscores).join(', ')}`,
              );
            }
          }
        }

        // Then list all exports with their metadata (no dash format)
        if (hasExports && page.exports) {
          for (const [exportName, exportMetadata] of Object.entries(page.exports)) {
            const hasProps = exportMetadata.props && exportMetadata.props.length > 0;
            const hasDataAttributes =
              exportMetadata.dataAttributes && exportMetadata.dataAttributes.length > 0;
            const hasCssVariables =
              exportMetadata.cssVariables && exportMetadata.cssVariables.length > 0;
            const hasParameters = exportMetadata.parameters && exportMetadata.parameters.length > 0;

            lines.push(`  - ${exportName}`);

            if (hasProps) {
              lines.push(`    - Props: ${exportMetadata.props!.map(escapeUnderscores).join(', ')}`);
            }
            if (hasParameters) {
              const paramsText = exportMetadata
                .parameters!.map((p) =>
                  Array.isArray(p)
                    ? `(${p.map(escapeUnderscores).join(', ')})`
                    : escapeUnderscores(p),
                )
                .join(', ');
              lines.push(`    - Parameters: ${paramsText}`);
            }
            if (exportMetadata.returns && exportMetadata.returns.length > 0) {
              lines.push(
                `    - Returns: ${exportMetadata.returns.map(escapeUnderscores).join(', ')}`,
              );
            }
            if (hasDataAttributes) {
              lines.push(
                `    - Data Attributes: ${exportMetadata.dataAttributes!.map(escapeUnderscores).join(', ')}`,
              );
            }
            if (hasCssVariables) {
              lines.push(
                `    - CSS Variables: ${exportMetadata.cssVariables!.map(escapeUnderscores).join(', ')}`,
              );
            }
          }
        }
        hasMetadataContent = true;
      }
      if (hasTypes && page.types) {
        lines.push(`- Types: ${page.types.join(', ')}`);
        hasMetadataContent = true;
      }
      lines.push('');
      lines.push('</details>');
      // Only add blank line if we actually added metadata content
      if (hasMetadataContent) {
        lines.push('');
      }
    }

    // Add embeddings as a comment if available
    if (page.embeddings && page.embeddings.length > 0) {
      lines.push(`[//]: # 'Embeddings: ${JSON.stringify(page.embeddings)}'`);
      lines.push('');
    }

    // Add read more link
    lines.push(`[Read more](${formatLinkUrl(page.path)})`);
    lines.push('');
  }

  // Add metadata marker (inside wrapper component if provided)
  lines.push(
    "[//]: # 'The above section is autogenerated, but the remainder of the file can be modified.'",
  );
  lines.push('');

  // Close wrapper component if provided
  if (indexWrapperComponent) {
    lines.push(`</${indexWrapperComponent}>`);
    lines.push('');
  }
  const TYPE_ANNOTATION =
    "/** @type {import('@mui/internal-docs-infra/createSitemap/types').NextMetadata} */";
  if (pageMetadata && Object.keys(pageMetadata).length > 0) {
    lines.push(
      `export const metadata =\n  ${TYPE_ANNOTATION} (${serializeJsValue(pageMetadata, 1)});`,
    );
  } else {
    lines.push(
      `export const metadata =\n  ${TYPE_ANNOTATION} (${serializeJsValue({ robots: { index: false }, other: { audience: 'private' } }, 1)});`,
    );
  }
  lines.push('');

  // Remove trailing empty line
  return `${lines.join('\n').trimEnd()}\n`;
}

/** An editable-region section heading and the page-list index where its pages begin. */
interface EditableSectionStart {
  section: PageIndexSection;
  startIndex: number;
}

/**
 * Yields each editable section heading paired with the `[startIndex, endIndex)` range of
 * pages listed under it — bounded by the start of the next heading (or the end of the list).
 * Shared by the two passes that walk these ranges so the bounding math lives in one place.
 */
function* sectionPageRanges(
  editableSectionStarts: EditableSectionStart[],
  pageCount: number,
): Generator<{ section: PageIndexSection; startIndex: number; endIndex: number }> {
  for (let sectionIndex = 0; sectionIndex < editableSectionStarts.length; sectionIndex += 1) {
    const { section, startIndex } = editableSectionStarts[sectionIndex];
    const endIndex =
      sectionIndex + 1 < editableSectionStarts.length
        ? editableSectionStarts[sectionIndex + 1].startIndex
        : pageCount;
    yield { section, startIndex, endIndex };
  }
}

/**
 * Resolves each editable section heading's route group from the first grouped page listed
 * under it, bounded by the start of the next section. The heading text is human-editable,
 * so the route group (stable) is the source of truth that keeps a renamed heading
 * associated with its pages. Bounding by the next section prevents an empty or placeholder
 * heading from adopting the following section's group. A heading with pages but no grouped
 * page (e.g. only external links) keeps a stable {@link syntheticSectionGroup} derived from
 * its text so it survives regeneration; a heading with no pages at all has nothing to key it
 * and is dropped. Duplicate headings for the same group collapse to the first, so downstream
 * rendering never double-lists a group. An empty result means the index is flat (no
 * route-group organization), even if it has editable-region headings.
 */
function resolveEditableSections(
  editableSectionStarts: EditableSectionStart[],
  pages: PageMetadata[],
): PageIndexSection[] {
  const resolvedSections: PageIndexSection[] = [];
  const seenGroups = new Set<string>();
  for (const { section, startIndex, endIndex } of sectionPageRanges(
    editableSectionStarts,
    pages.length,
  )) {
    // The route group is the source of truth that keeps a renamed heading with its pages; a
    // heading over only external links keeps a synthetic id so it survives regeneration, while a
    // heading over local pages stays flat (its H2 detail sections are untouched). Duplicate
    // headings for a group collapse to the first.
    const group = resolveSectionGroup(
      section.title,
      pages.slice(startIndex, endIndex).map((page) => page.path),
    );
    if (group && !seenGroups.has(group)) {
      seenGroups.add(group);
      section.group = group;
      resolvedSections.push(section);
    }
  }
  return resolvedSections;
}

/**
 * Records, on each ungrouped page, the route group of the section it is physically listed
 * under (once {@link resolveEditableSections} has keyed each heading to a group). A page
 * whose own path has a route group derives its section from the path and is left untouched;
 * a page with no route group (e.g. an external link) keeps the placement a human gave it so
 * it does not fall back to the top of the index on the next regeneration. Runs in-place.
 */
function assignPlacedSections(
  editableSectionStarts: EditableSectionStart[],
  pages: PageMetadata[],
): void {
  for (const { section, startIndex, endIndex } of sectionPageRanges(
    editableSectionStarts,
    pages.length,
  )) {
    // `resolveEditableSections` sets `section.group` on resolved headings and leaves dropped
    // or placeholder headings with an empty group — skip those (their pages stay ungrouped).
    if (!section.group) {
      continue;
    }
    for (let pageIndex = startIndex; pageIndex < endIndex; pageIndex += 1) {
      if (routeGroupOfPath(pages[pageIndex].path) === undefined) {
        pages[pageIndex].sectionGroup = section.group;
      }
    }
  }
}

/**
 * Parses markdown content and extracts page metadata using unified
 */
export async function markdownToMetadata(markdown: string): Promise<PagesMetadata | null> {
  const tree = unified().use(remarkParse).parse(markdown);

  let title: string | null = null;
  let description: string | undefined;
  let pageMetadata: Record<string, unknown> | undefined;
  let indexWrapperComponent: string | undefined;
  const pages: PageMetadata[] = [];
  // Track the title from the editable list for each page (by slug)
  // Used to detect user overrides after the detail section is parsed
  const listTitles = new Map<string, string>();
  let currentSection: 'header' | 'editable' | 'details' | 'metadata' = 'header';
  let currentPage: Partial<PageMetadata> | null = null;
  // Route-group section headings encountered in the editable region (grouped indexes),
  // each with the page-list position where it starts. The section's `group` is inferred
  // from the first page listed under it once the editable region is fully parsed.
  const editableSectionStarts: EditableSectionStart[] = [];
  // Sections resolved to their route groups (empty ⇒ flat index). Resolved when leaving
  // the editable region so the detail parser uses the same grouped/flat signal as output.
  let resolvedSections: PageIndexSection[] = [];
  let sectionsResolved = false;
  // Title of the "## Details" wrapper heading in a grouped index's detail region.
  let detailsSectionTitle: string | undefined;
  // Only the first H2 in the detail region is the "## Details" wrapper; later H2s are ignored.
  let detailsWrapperSeen = false;

  // Merges the in-progress detail page's parsed fields back into its list entry (matched
  // by slug). Called whenever the detail parser moves off the current page.
  const flushCurrentPage = () => {
    const page = currentPage;
    if (!page?.slug) {
      return;
    }
    const foundIndex = pages.findIndex((existing) => existing.slug === page.slug);
    if (foundIndex !== -1) {
      pages[foundIndex] = { ...pages[foundIndex], ...page } as PageMetadata;
    }
  };

  // Visit all nodes in the AST
  visit(tree, (node, index, parent) => {
    // Track sections based on definition nodes (HTML-style comments)
    if (node.type === 'definition') {
      const defNode = node as DefinitionNode;
      if (
        defNode.title?.includes('following list can be modified') ||
        defNode.title?.includes('following list order')
      ) {
        currentSection = 'editable';
        return;
      }
      if (defNode.title?.includes('DO NOT EDIT AFTER THIS LINE')) {
        currentSection = 'details';
        // Resolve sections now that the whole editable region (headings + list) is parsed,
        // so the detail parser's grouped/flat decision matches the resolved sections the
        // file was rendered from — not the mere presence of an editable-region heading.
        resolvedSections = resolveEditableSections(editableSectionStarts, pages);
        // Remember, per page, the section a human placed it under, so a page with no route
        // group of its own (e.g. an external link) stays under that header instead of
        // falling to the top on the next regeneration. Route-grouped pages don't need this —
        // they sort by their path — so only ungrouped pages are tagged.
        assignPlacedSections(editableSectionStarts, pages);
        sectionsResolved = true;
        return;
      }
      if (
        defNode.title?.includes('remainder of the file can be modified') ||
        // TODO: Remove this old marker check once all index files have been migrated to the new format.
        defNode.title?.includes('following metadata can be modified')
      ) {
        currentSection = 'metadata';
        return;
      }
      // Parse embeddings from comment
      if (currentPage && defNode.title?.includes('Embeddings:')) {
        const embeddingsText = defNode.title.replace('Embeddings:', '').trim();
        try {
          currentPage.embeddings = JSON.parse(embeddingsText);
        } catch (error) {
          console.error('Failed to parse embeddings:', error);
        }
        return;
      }
    }

    // Extract wrapper component from HTML nodes (e.g., <PagesIndex>)
    if (node.type === 'html' && !indexWrapperComponent) {
      const htmlNode = node as { type: 'html'; value: string };
      // Match opening tag like <PagesIndex> or <ComponentsIndex>
      const openingTagMatch = htmlNode.value.match(/^<([A-Z][a-zA-Z0-9]*)>$/);
      if (openingTagMatch) {
        indexWrapperComponent = openingTagMatch[1];
      }
    }

    // Extract main title (H1)
    if (node.type === 'heading') {
      const headingNode = node as HeadingNode;
      if (headingNode.depth === 1) {
        title = extractPlainTextFromNode(headingNode);
        currentSection = 'header';
        return;
      }
    }

    // Route-group section heading in the editable region (grouped index). Any heading
    // below the H1 title is a section boundary (the editable region has no other
    // headings); its route group is inferred later from the pages listed under it.
    if (
      currentSection === 'editable' &&
      node.type === 'heading' &&
      (node as HeadingNode).depth >= 2
    ) {
      const headingNode = node as HeadingNode;
      const section: PageIndexSection = {
        group: '',
        title: extractPlainTextFromNode(headingNode),
        ...(headingNode.depth !== 2 ? { depth: headingNode.depth } : {}),
      };
      editableSectionStarts.push({ section, startIndex: pages.length });
      return;
    }

    // Parse description in header section (paragraph after H1, before editable marker)
    if (currentSection === 'header' && node.type === 'paragraph' && parent?.type === 'root') {
      const paragraphNode = node as ParagraphNode;
      const paragraphText = extractPlainTextFromNode(paragraphNode);
      if (paragraphText && !description) {
        description = paragraphText;
      }
      return;
    }

    // Parse editable list items - check if we're in a paragraph that's a child of a listItem
    if (currentSection === 'editable' && node.type === 'paragraph' && parent?.type === 'listItem') {
      const paragraphNode = node as ParagraphNode;
      if (paragraphNode.children) {
        // Look for links in the paragraph
        const links = paragraphNode.children.filter(
          (child: any) => child.type === 'link',
        ) as LinkNode[];

        if (links.length === 0) {
          // No links found, skip this item
          return;
        }

        if (links.length === 1) {
          // Single link format: - [Title](./path) [Tag1] [Tag2]
          // This is for external links or pages that don't have detail sections
          const singleLink = links[0];
          const pageTitle = extractPlainTextFromNode(singleLink);
          const path = singleLink.url;

          // Generate slug from title for consistency
          const slug = titleToSlug(pageTitle);

          // Extract tags from text nodes after the link
          // Tags are in the format [Tag] where Tag can be New, Hot, Beta, External, etc.
          const tags: string[] = [];
          let foundLink = false;
          for (const child of paragraphNode.children) {
            if (child === singleLink) {
              foundLink = true;
              continue;
            }
            if (foundLink && child.type === 'text') {
              // Match [Tag] patterns in the text
              const tagRegex = /\[(\w+)\]/g;
              let match = tagRegex.exec(child.value);
              while (match !== null) {
                tags.push(match[1]);
                match = tagRegex.exec(child.value);
              }
            }
          }

          // These entries are preserved as-is in the editable section
          // They won't have detail sections generated
          pages.push({
            slug,
            path,
            title: pageTitle,
            description: 'No description available',
            tags: tags.length > 0 ? tags : undefined,
            skipDetailSection: true, // Mark as external/single-link entry
          });
          listTitles.set(slug, pageTitle);
        } else if (links.length >= 2) {
          const firstChild = paragraphNode.children[0];

          if (
            firstChild &&
            firstChild.type === 'text' &&
            (firstChild as any).value.includes(' - (')
          ) {
            // Format: Title [Tags] - (Status, [Outline](#slug), [Contents](./path))
            const firstText = (firstChild as any).value as string;
            const dashParenIndex = firstText.lastIndexOf(' - (');
            const titlePart = firstText.substring(0, dashParenIndex);

            // Extract tags from title part
            const tags: string[] = [];
            const tagRegex = /\[([^\]]+)\]/g;
            let match = tagRegex.exec(titlePart);
            while (match !== null) {
              tags.push(match[1]);
              match = tagRegex.exec(titlePart);
            }
            const cleanTitle = titlePart.replace(/\s*\[[^\]]+\]/g, '').trim();

            // Find Outline and Contents links
            const outlineLink = links.find(
              (l) => extractPlainTextFromNode(l) === 'Outline' || l.url.startsWith('#'),
            );
            const contentsLink = links.find(
              (l) => extractPlainTextFromNode(l) === 'Contents' || !l.url.startsWith('#'),
            );

            if (outlineLink && contentsLink) {
              const slug = outlineLink.url.replace('#', '');
              const pagePath = contentsLink.url;

              // Parse status label from the text before the first link
              // Format: " - (Status, " or " - ("
              let parsedAudience: Audience | undefined;
              let isIndex = false;
              const afterDashParen = firstText.substring(dashParenIndex + 4); // after ' - ('
              if (afterDashParen.length > 0) {
                // Status label is the text before the first comma that precedes a link
                const commaIndex = afterDashParen.indexOf(',');
                if (commaIndex >= 0) {
                  const statusStr = afterDashParen.substring(0, commaIndex).trim();
                  if (statusStr.length > 0) {
                    const status = parseStatusLabel(statusStr);
                    parsedAudience = status.audience;
                    isIndex = status.index;
                  }
                }
              }

              pages.push({
                slug,
                path: pagePath,
                title: cleanTitle,
                description: 'No description available',
                tags: tags.length > 0 ? tags : undefined,
                audience: parsedAudience,
                index: isIndex || undefined,
              } satisfies PageMetadata);
              listTitles.set(slug, cleanTitle);
            }
          } else {
            // TODO: Remove this old format parsing once all index files have been migrated.
            // Old format: - [Title](#slug) [Tag1] [Tag2] - [Full Docs](./path/page.mdx)
            const sectionLink = links[0];
            const docsLink = links[1];

            const pageTitle = extractPlainTextFromNode(sectionLink);
            const slug = sectionLink.url.replace('#', '');
            const pagePath = docsLink.url;

            const tags: string[] = [];
            let foundSectionLink = false;
            let foundDocsLink = false;
            for (const child of paragraphNode.children) {
              if (child === sectionLink) {
                foundSectionLink = true;
                continue;
              }
              if (child === docsLink) {
                foundDocsLink = true;
                break;
              }
              if (foundSectionLink && !foundDocsLink && child.type === 'text') {
                const tagRegex = /\[(\w+)\]/g;
                let match = tagRegex.exec(child.value);
                while (match !== null) {
                  tags.push(match[1]);
                  match = tagRegex.exec(child.value);
                }
              }
            }

            pages.push({
              slug,
              path: pagePath,
              title: pageTitle,
              description: 'No description available',
              tags: tags.length > 0 ? tags : undefined,
            });
            listTitles.set(slug, pageTitle);
          }
        }
      }
      return;
    }

    // Parse detail sections
    if (currentSection === 'details') {
      // In grouped indexes the detail region is wrapped in a single "## Details" H2
      // and each page is an H3; flat indexes render each page directly as an H2. Keyed off
      // resolved route-group sections (not raw headings), matching how the file was rendered.
      const grouped = resolvedSections.length > 0;
      const detailDepth = detailHeadingDepth(grouped);

      if (node.type === 'heading') {
        const headingNode = node as HeadingNode;
        const headingTitle = extractPlainTextFromNode(headingNode);
        // A detail heading whose title/slug matches a listed page is that page's detail section
        // (slug matching covers a user-renamed list item where list title ≠ heading title). This
        // decides both whether an H2 is the wrapper and whether a malformed H2 detail is a page.
        const headingSlug = titleToSlug(headingTitle);
        const listedPage =
          pages.find((page) => page.title === headingTitle) ??
          pages.find((page) => page.slug === headingSlug);

        // The first H2 that is NOT a listed page is the "## Details" wrapper (grouped only): record
        // its title, not a page. Later stray H2s fall through (ignored) so they don't clobber the
        // wrapper title or discard the in-progress page. An H2 that DOES match a listed page is a
        // malformed per-page detail (grouped editable region, but flat H2 details instead of the
        // "## Details" + H3 convention); it is parsed as a page below rather than swallowed as the
        // wrapper (which would re-render as a bogus "## <page>" heading).
        if (grouped && !detailsWrapperSeen && headingNode.depth === 2 && !listedPage) {
          detailsWrapperSeen = true;
          flushCurrentPage();
          currentPage = null;
          detailsSectionTitle = headingTitle;
          return;
        }

        // Start of a page's detail section: the grouped detail depth (H3), the flat depth (H2), or
        // a page-matching H2 in a grouped index — so a malformed file's descriptions aren't dropped.
        const startsPageSection =
          headingNode.depth === detailDepth ||
          (grouped && headingNode.depth === 2 && Boolean(listedPage));
        if (startsPageSection) {
          // Save previous page if exists
          flushCurrentPage();
          currentPage = listedPage
            ? { slug: listedPage.slug, title: headingTitle }
            : { slug: headingSlug, title: headingTitle };
          return;
        }
      }

      // Parse description (first paragraph after title) and keywords/sections
      if (currentPage && node.type === 'paragraph') {
        const paragraphNode = node as ParagraphNode;
        const paragraphText = extractTextFromNode(paragraphNode);

        // Check if we're in a list item
        if (parent?.type === 'listItem') {
          // Parse keywords
          if (paragraphText.startsWith('Keywords:')) {
            const keywordsText = paragraphText.replace('Keywords:', '').trim();
            currentPage.keywords = keywordsText.split(',').map((k) => k.trim());
            return;
          }

          // Parse exports - they're in a nested list within the same parent list item
          if (paragraphText.startsWith('Exports:')) {
            const result = parseExportsFromListItem(parent as any);
            if (result.exports) {
              currentPage.exports = result.exports;
            }
            if (result.parts) {
              currentPage.parts = result.parts;
            }
            return;
          }

          // Parse types
          if (paragraphText.startsWith('Types:')) {
            const typesText = paragraphText.replace('Types:', '').trim();
            if (typesText) {
              currentPage.types = typesText.split(',').map((t) => t.trim());
            }
            return;
          }

          // Parse sections - now they're in a nested list within the same parent list item
          if (paragraphText.startsWith('Sections:')) {
            // Find the nested list within this list item
            const listItem = parent as any;
            const nestedList = listItem.children?.find((child: any) => child.type === 'list');

            if (nestedList && nestedList.children) {
              currentPage.sections = parseHeadingSections(nestedList);
            } else {
              currentPage.sections = {};
            }
            return;
          }
        }

        // Extract path from Read more link for robust page matching.
        // If the current page's slug doesn't match any page in the list
        // (e.g., because titleToSlug(heading) ≠ actual slug), the path match
        // provides a final correction.
        if (paragraphText.startsWith('[Read more]')) {
          if (currentPage) {
            const linkNode = paragraphNode.children.find((child: any) => child.type === 'link') as
              | LinkNode
              | undefined;
            if (linkNode) {
              const readMorePath = linkNode.url;
              const matchedPage = pages.find((p) => p.path === readMorePath);
              if (matchedPage && currentPage.slug !== matchedPage.slug) {
                currentPage.slug = matchedPage.slug;
              }
            }
          }
          return;
        }

        // Parse description (first paragraph after title, not in a list)
        if (!currentPage.description && parent?.type !== 'listItem') {
          currentPage.description = paragraphText;
          // Store the AST nodes with position info stripped for clean serialization
          if (paragraphNode.children) {
            currentPage.descriptionMarkdown = stripPositions(paragraphNode.children);
          }
          return;
        }
      }

      // Parse image
      if (currentPage && node.type === 'image') {
        const imageNode = node as ImageNode;
        currentPage.image = {
          url: imageNode.url,
          alt: imageNode.alt || currentPage.title || currentPage.slug || '',
        };
        return;
      }
    }

    // Parse metadata export section (code block or raw export statement after metadata comment)
    if (currentSection === 'metadata' && node.type === 'code') {
      const codeNode = node as CodeNode;
      const codeValue = codeNode.value;
      // Parse the export const metadata = /** @type ... */ ({ ... }) or { ... } statement
      const metadataMatch = codeValue.match(
        /export\s+const\s+metadata\s*=\s*(?:\/\*\*[^*]*\*\/\s*\()?\s*(\{[\s\S]*\})\)?/,
      );
      if (metadataMatch) {
        try {
          // Use Function constructor to safely parse the object literal
          // eslint-disable-next-line no-new-func
          pageMetadata = new Function(`return ${metadataMatch[1]}`)();
        } catch (error) {
          console.error('Failed to parse page metadata:', error);
        }
      }
      return;
    }
  });

  // Also try to parse metadata from raw export statement in the markdown
  // This handles MDX files where the export is not in a code block
  // The regex allows optional HTML closing tags (e.g., </PagesIndex>) between the marker and the export
  // Greedy `[\s\S]*` ensures the capture extends to the LAST `\n\s*\}` (outermost closing brace)
  // rather than stopping at an inner closing brace. This is safe because the metadata
  // export is always the last statement in the file.
  // Strip fenced code blocks to avoid matching markers inside examples
  const markdownWithoutCodeBlocks = markdown.replace(/```[\s\S]*?```/g, '');
  const metadataExportMatch =
    markdownWithoutCodeBlocks.match(
      /\[\/\/\]: # 'The above section is autogenerated, but the remainder of the file can be modified\.'[\s\S]*?export\s+const\s+metadata\s*=\s*(?:\/\*\*[^*]*\*\/\s*\()?\s*(\{[\s\S]*\n\s*\})\)?\s*;?/,
    ) ??
    // TODO: Remove this old marker match once all index files have been migrated to the new format.
    markdownWithoutCodeBlocks.match(
      /\[\/\/\]: # 'This (?:section|file) is autogenerated, but the following metadata can be modified\.'[\s\S]*?export\s+const\s+metadata\s*=\s*(?:\/\*\*[^*]*\*\/\s*\()?\s*(\{[\s\S]*\n\s*\})\)?\s*;?/,
    );
  if (metadataExportMatch && !pageMetadata) {
    try {
      // eslint-disable-next-line no-new-func
      pageMetadata = new Function(`return ${metadataExportMatch[1]}`)();
    } catch (error) {
      console.error('Failed to parse page metadata from raw export:', error);
    }
  }

  // Save last page if exists
  flushCurrentPage();

  // Detect title overrides: compare the list title with the heading title.
  // After the detail section is parsed, page.title reflects the heading's title.
  // If the list had a different title, the user renamed it — store as displayTitle.
  for (const page of pages) {
    const listTitle = listTitles.get(page.slug);
    if (listTitle && listTitle !== page.title) {
      page.displayTitle = listTitle;
    }
  }

  // Fallback for a malformed file that has editable headings but no "DO NOT EDIT" marker
  // (so the transition above never resolved them). Mirror the normal transition: also record
  // each page's manual placement, so an ungrouped link filed under a heading is not dropped.
  if (!sectionsResolved) {
    resolvedSections = resolveEditableSections(editableSectionStarts, pages);
    assignPlacedSections(editableSectionStarts, pages);
  }

  if (!title) {
    return null;
  }

  return {
    title,
    description,
    pages,
    sections: resolvedSections.length > 0 ? resolvedSections : undefined,
    detailsSectionTitle,
    pageMetadata,
    indexWrapperComponent,
  };
}

/**
 * Extracts plain text content from any mdast node without markdown formatting
 * Used for titles and other places where we don't want markdown syntax
 */
function extractPlainTextFromNode(node: any): string {
  if (node.type === 'text') {
    return node.value;
  }
  if (node.type === 'inlineCode') {
    return node.value;
  }
  if (node.children) {
    const extractedText = node.children
      .map((child: any) => extractPlainTextFromNode(child))
      .join('');
    // For paragraph nodes, replace sequences of regular whitespace (spaces, tabs, newlines)
    // with a single space, but preserve non-breaking spaces and other special whitespace
    if (node.type === 'paragraph') {
      return collapseInlineWhitespace(extractedText);
    }
    return extractedText;
  }
  return '';
}

/**
 * Extracts text content from any mdast node
 * Preserves markdown formatting like inline code and links
 */
function extractTextFromNode(node: any): string {
  if (node.type === 'text') {
    return node.value;
  }
  if (node.type === 'inlineCode') {
    return `\`${node.value}\``;
  }
  if (node.type === 'link') {
    const linkText = node.children.map((child: any) => extractTextFromNode(child)).join('');
    return `[${linkText}](${node.url})`;
  }
  if (node.type === 'emphasis') {
    const emphasisText = node.children.map((child: any) => extractTextFromNode(child)).join('');
    // Prettier serializes emphasis with underscores; match it to keep the
    // generated file stable when prettier formats it afterwards.
    return `_${emphasisText}_`;
  }
  if (node.type === 'strong') {
    const strongText = node.children.map((child: any) => extractTextFromNode(child)).join('');
    return `**${strongText}**`;
  }
  if (node.children) {
    const extractedText = node.children.map((child: any) => extractTextFromNode(child)).join('');
    // For paragraph nodes, replace sequences of regular whitespace (spaces, tabs, newlines)
    // with a single space, but preserve non-breaking spaces and other special whitespace
    if (node.type === 'paragraph') {
      return collapseInlineWhitespace(extractedText);
    }
    return extractedText;
  }
  return '';
}

/**
 * Converts a title to a slug (simple version)
 */
function titleToSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
