name: PR Releases

on:
  workflow_call:
    inputs:
      # For backwards compatibility
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: ''
      pr-comment:
        description: 'Allows comments from pkg.pr.new bot'
        type: boolean
        required: false
        default: false

permissions: {}

jobs:
  pkg-releases:
    name: pkg.pr.new releases
    if: ${{ github.repository_owner == 'mui' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # fetch all tags which are required for `pnpm release:changelog`
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Use specific Node.js version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: ${{ inputs.node-version != '' }}
        with:
          node-version: ${{ inputs.node-version }}
      - name: Use Node.js version from repo
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: ${{ inputs.node-version == '' }}
        with:
          node-version-file: 'package.json'
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm release:build
      - name: Publish packages to pkg.pr.new
        uses: mui/mui-public/.github/actions/ci-publish@9590da6ae303c6afa7e67aebb6bc46232fac164e # master
        with:
          pr-comment: ${{ inputs.pr-comment }}
