name: Add closing message to issue

on:
  issues:
    types:
      - closed
  workflow_call:

permissions: {}

jobs:
  add-comment:
    runs-on: ubuntu-latest
    name: Check author permission and add closing message
    permissions:
      issues: write
    steps:
      - name: Check out mui-public repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Check this repository out, otherwise the script won't be available,
          # as it otherwise checks out the repository where the workflow caller is located
          repository: mui/mui-public
      - name: Add closing message
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const script = require('./.github/workflows/scripts/issues/addClosingMessage.js');
            await script({core, github, context});
